/*
 * Optional build-time-signed AArch64 execution path for the real SoC loop.
 *
 * This file never emits executable memory. It caches decoded data records and
 * dispatches into ordinary text generated by tools/gen_a64_static.py. The
 * Product load records consult only arm_cpu's already-proved plain-RAM read
 * cache. A miss performs no access and returns to arm_step(), which remains the
 * sole owner of MMU walks, faults and MMIO. Stores remain literal because the
 * host write observer is architecturally visible to the frontend. A zero
 * return is always a clean request for the existing arm_step() path.
 */
#include "a64_static_engine.h"

#include <stdlib.h>
#include <string.h>

#if defined(S5LBOX_STATIC_A64_ENGINE)
#include "a64_static.h"

#define STATIC_A64_CACHE_ENTRIES 1024u
#define STATIC_A64_RAW_BYTES (A64_STATIC_MAX_INSNS * 4u)
#define STATIC_A64_CHAIN_INSNS A64_STATIC_MAX_INSNS

typedef struct {
    const uint8_t *fetch_host;
    uint32_t pc;
    uint32_t fetch_gen;
    uint8_t raw[STATIC_A64_RAW_BYTES];
    uint8_t raw_len;
    bool fetch_priv;
    bool thumb;
    bool valid;
    bool supported;
    a64_static_block_t block;
} static_a64_entry_t;

typedef struct {
    bool enabled;
    bool persistent;
    bool graph_enabled;
    uint64_t retired;
    uint64_t chained_blocks;
    uint64_t persistent_chained_blocks;
    uint64_t graph_chained_blocks;
    static_a64_entry_t cache[STATIC_A64_CACHE_ENTRIES];
    a64_static_graph_node_t graph_nodes[A64_STATIC_GRAPH_SLOTS];
} static_a64_state_t;

static static_a64_state_t *static_state(const s5l8900_t *m) {
    return m ? (static_a64_state_t *)m->static_a64_state : NULL;
}

static unsigned cache_index(uint32_t pc, bool thumb, uint32_t generation) {
    uint32_t key = pc >> (thumb ? 1u : 2u);
    key ^= generation * UINT32_C(0x9e3779b1);
    if (thumb) key ^= UINT32_C(0x85ebca6b);
    return key & (STATIC_A64_CACHE_ENTRIES - 1u);
}

static bool entry_matches(const static_a64_entry_t *entry,
                          const arm_cpu_t *cpu, const uint8_t *bytes,
                          uint32_t pc, bool thumb, bool priv,
                          unsigned available_len) {
    return entry->valid && entry->fetch_host == cpu->fetch_host &&
           entry->pc == pc && entry->fetch_gen == cpu->fetch_gen &&
           entry->fetch_priv == priv && entry->thumb == thumb &&
           entry->raw_len != 0u && entry->raw_len <= available_len &&
           memcmp(entry->raw, bytes, entry->raw_len) == 0;
}

static bool decode_longest(const uint8_t *bytes, unsigned candidate_insns,
                           bool thumb, uint32_t pc,
                           a64_static_block_t *out) {
    for (unsigned count = candidate_insns; count != 0u; count--) {
        if (a64_static_decode_read_hits_bytes_at(bytes, count, thumb, pc,
                                                 out))
            return true;
    }
    return false;
}

static unsigned graph_index(uint32_t pc, bool thumb) {
    return (pc & UINT32_C(0x3ff)) >> (thumb ? 1u : 2u);
}

static void invalidate_entry(static_a64_state_t *state,
                             static_a64_entry_t *entry) {
    if (!state || !entry) return;
    a64_static_graph_node_t *node =
        &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
    if (node->owner == entry) {
        node->valid = 0u;
        node->supported = 0u;
    }
    entry->valid = false;
}

static void publish_graph_node(static_a64_state_t *state,
                               static_a64_entry_t *entry) {
    a64_static_graph_node_t *node;
    if (!state || !entry) return;
    node = &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
    memset(node, 0, sizeof *node);
    node->owner = entry;
    node->fetch_host = entry->fetch_host;
    node->uops = entry->block.uops;
    node->pc = entry->pc;
    node->fetch_gen = entry->fetch_gen;
    node->insn_count = entry->block.insn_count;
    node->raw_len = entry->raw_len;
    memcpy(node->raw, entry->raw, entry->raw_len);
    node->fetch_priv = entry->fetch_priv ? 1u : 0u;
    node->thumb = entry->thumb ? 1u : 0u;
    node->valid = entry->valid ? 1u : 0u;
    node->supported = entry->supported ? 1u : 0u;
}

static void decode_entry(static_a64_state_t *state, static_a64_entry_t *entry,
                         const arm_cpu_t *cpu,
                         const uint8_t *bytes, uint32_t pc, bool thumb,
                         bool priv, unsigned candidate_insns,
                         unsigned available_len) {
    const unsigned width = thumb ? 2u : 4u;

    invalidate_entry(state, entry);
    memset(entry, 0, sizeof *entry);
    entry->fetch_host = cpu->fetch_host;
    entry->pc = pc;
    entry->fetch_gen = cpu->fetch_gen;
    entry->fetch_priv = priv;
    entry->thumb = thumb;
    entry->valid = true;

    /* Decode the longest exact prefix. Product loads carry a guarded DREAD hit;
     * stores and unsupported forms still shorten to an earlier exact prefix. */
    if (decode_longest(bytes, candidate_insns, thumb, pc, &entry->block)) {
        entry->supported = true;
        entry->raw_len = (uint8_t)(entry->block.insn_count * width);
    } else {
        /* If instruction zero is unsupported, later bytes cannot make any
         * prefix executable while its own encoding is unchanged. Remembering
         * one instruction therefore detects every semantic change relevant to
         * this negative entry without rescanning the rest of the candidate. */
        entry->raw_len = (uint8_t)width;
    }
    /* A cached supported prefix depends only on the bytes it can execute.
     * Bytes after that prefix may later become supportable; retaining the
     * shorter block is still exact because arm_step() owns the next PC. The
     * old full-candidate witness compared as many as 64 bytes at every hot
     * graph head even when the block contained one instruction. */
    if (entry->raw_len > available_len) {
        invalidate_entry(state, entry);
        return;
    }
    memcpy(entry->raw, bytes, entry->raw_len);
    publish_graph_node(state, entry);
}

typedef struct {
    static_a64_state_t *state;
    s5l8900_t *machine;
    uint32_t fetch_block;
    a64_static_block_t bounded_block;
    static_a64_entry_t *last_entry;
} static_a64_chain_context_t;

static const a64_static_block_t *select_persistent_block(
    static_a64_chain_context_t *context, uint32_t pc, unsigned remaining) {
    s5l8900_t *m;
    arm_cpu_t *cpu;
    uint32_t fetch_block;
    unsigned width;
    unsigned offset;
    unsigned candidate_insns;
    unsigned raw_len;
    bool thumb;
    bool priv;
    const uint8_t *bytes;
    static_a64_entry_t *entry;

    if (!context || !remaining) return NULL;
    m = context->machine;
    cpu = &m->cpu;

    /* This is the same fail-closed head contract as the legacy C loop. Guest
     * general registers/NZCV remain pinned across this callback, so selection
     * deliberately consults only state that the signed subset cannot mutate. */
    if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
        !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
        (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
        (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
        return NULL;

    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    width = thumb ? 2u : 4u;
    if ((pc & (width - 1u)) != 0u) return NULL;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (fetch_block != context->fetch_block || !cpu->fetch_host ||
        cpu->fetch_blk != fetch_block || cpu->fetch_gen != cpu->tlb_gen ||
        cpu->fetch_priv != priv)
        return NULL;

    offset = pc - fetch_block;
    candidate_insns = (0x400u - offset) / width;
    if (candidate_insns > A64_STATIC_MAX_INSNS)
        candidate_insns = A64_STATIC_MAX_INSNS;
    if (!candidate_insns) return NULL;
    raw_len = candidate_insns * width;
    bytes = cpu->fetch_host + offset;

    entry = &context->state->cache[
        cache_index(pc, thumb, cpu->fetch_gen)];
    if (!entry_matches(entry, cpu, bytes, pc, thumb, priv, raw_len))
        decode_entry(context->state, entry, cpu, bytes, pc, thumb, priv,
                     candidate_insns, raw_len);
    context->last_entry = entry;
    if (!entry->supported) return NULL;
    if (entry->block.insn_count <= remaining) return &entry->block;

    /* A bounded prefix lives in the persistent invocation's outer C frame;
     * the next callback cannot overwrite it until this block has completed. */
    if (!decode_longest(bytes, remaining, thumb, pc,
                        &context->bounded_block))
        return NULL;
    return &context->bounded_block;
}

static const a64_static_block_t *persistent_next(void *opaque, uint32_t pc,
                                                 unsigned remaining) {
    return select_persistent_block(
        (static_a64_chain_context_t *)opaque, pc, remaining);
}
#endif

bool s5l8900_static_a64_available(void) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    return a64_static_host_available();
#else
    return false;
#endif
}

bool s5l8900_static_a64_set_enabled(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->enabled = false;
        return true;
    }
    if (!a64_static_host_available()) return false;
    if (!state) {
        state = (static_a64_state_t *)calloc(1u, sizeof *state);
        if (!state) return false;
        m->static_a64_state = state;
    }
    state->enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_persistent(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->persistent = false;
        return true;
    }
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->graph_enabled = false;
    state->persistent = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_graph(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->graph_enabled = false;
        return true;
    }
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->persistent = false;
    state->graph_enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

uint64_t s5l8900_static_a64_retired(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_persistent_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->persistent_chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_graph_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->graph_chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

unsigned s5l8900_static_a64_cached_witness_bytes(const s5l8900_t *m,
                                                 uint32_t pc, bool thumb) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    if (!state) return 0u;
    for (unsigned i = 0u; i < STATIC_A64_CACHE_ENTRIES; i++) {
        const static_a64_entry_t *entry = &state->cache[i];
        if (entry->valid && entry->pc == pc && entry->thumb == thumb)
            return entry->raw_len;
    }
#else
    (void)m;
    (void)pc;
    (void)thumb;
#endif
    return 0u;
}

#if defined(S5LBOX_STATIC_A64_ENGINE)
static unsigned try_persistent(s5l8900_t *m, static_a64_state_t *state,
                               unsigned budget) {
    arm_cpu_t *cpu = &m->cpu;
    static_a64_chain_context_t context = {
        .state = state,
        .machine = m,
        .fetch_block = cpu->r[15] & ~UINT32_C(0x3ff)
    };
    const a64_static_block_t *first =
        select_persistent_block(&context, cpu->r[15], budget);
    unsigned completed = 0u;
    unsigned blocks = 0u;

    if (!first) return 0u;
    if (!a64_static_run_read_hits_chain(cpu, first, m->ram, m->ram_size,
                                        budget, persistent_next, &context,
                                        &completed, &blocks)) {
        /* A pre-execution contract mismatch must not become a sticky cache
         * hit. Runtime read/VFP misses are successful exact-prefix returns. */
        if (context.last_entry)
            invalidate_entry(state, context.last_entry);
        return 0u;
    }
    state->retired += completed;
    if (blocks > 1u) {
        state->chained_blocks += blocks - 1u;
        state->persistent_chained_blocks += blocks - 1u;
    }
    return completed;
}

static unsigned try_graph(s5l8900_t *m, static_a64_state_t *state,
                          unsigned budget) {
    arm_cpu_t *cpu = &m->cpu;
    static_a64_chain_context_t context = {
        .state = state,
        .machine = m,
        .fetch_block = cpu->r[15] & ~UINT32_C(0x3ff)
    };
    const a64_static_block_t *first =
        select_persistent_block(&context, cpu->r[15], budget);
    unsigned completed = 0u;
    unsigned blocks = 0u;

    if (!first) return 0u;
    /* The direct table is intentionally scoped by offset, so a descriptor at
     * the same offset in another 1 KiB fetch block may have replaced this
     * cache entry's node. Ensure the C-validated first head is published, but
     * leave an already-owned valid node untouched on the common hot hit. This
     * lets a returning block recover without recopying 128 bytes per entry. */
    {
        static_a64_entry_t *entry = context.last_entry;
        a64_static_graph_node_t *node =
            &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
        if (node->owner != entry || !node->valid || !node->supported)
            publish_graph_node(state, entry);
    }
    if (!a64_static_run_read_hits_graph(cpu, first, m->ram, m->ram_size,
                                        budget, state->graph_nodes, &completed,
                                        &blocks)) {
        if (context.last_entry)
            invalidate_entry(state, context.last_entry);
        return 0u;
    }
    state->retired += completed;
    if (blocks > 1u) {
        state->chained_blocks += blocks - 1u;
        state->graph_chained_blocks += blocks - 1u;
    }
    return completed;
}
#endif

unsigned s5l8900_static_a64_try(s5l8900_t *m, unsigned max_insns) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    arm_cpu_t *cpu;
    unsigned budget;
    unsigned retired = 0u;
    unsigned executed_blocks = 0u;

    if (!state || !state->enabled || !max_insns ||
        !a64_static_host_available() || !m->ram || !m->ram_size ||
        (m->ram_size & (m->ram_size - 1u)) != 0u)
        return 0u;

    cpu = &m->cpu;
    budget = max_insns < STATIC_A64_CHAIN_INSNS
           ? max_insns : STATIC_A64_CHAIN_INSNS;
    if (state->graph_enabled) return try_graph(m, state, budget);
    if (state->persistent) return try_persistent(m, state, budget);

    while (retired < budget) {
        uint32_t pc;
        uint32_t fetch_block;
        unsigned width;
        unsigned offset;
        unsigned candidate_insns;
        unsigned raw_len;
        unsigned remaining = budget - retired;
        unsigned completed = 0u;
        bool thumb;
        bool priv;
        const uint8_t *bytes;
        static_a64_entry_t *entry;
        a64_static_block_t bounded_block;
        const a64_static_block_t *run_block;

        /* Recheck every head. Signed instructions cannot change the MMU,
         * privilege, interrupt masks or instruction state, but keeping these
         * gates local makes that invariant fail closed if the subset grows. */
        if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
            !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
            (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
            (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
            break;

        pc = cpu->r[15];
        thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
        priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
        width = thumb ? 2u : 4u;
        if ((pc & (width - 1u)) != 0u) break;

        fetch_block = pc & ~UINT32_C(0x3ff);
        /* A cross-block target must return to arm_step(), which alone owns
         * instruction translation, MMU faults and the new fetch witness. */
        if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
            cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)
            break;

        offset = pc - fetch_block;
        candidate_insns = (0x400u - offset) / width;
        if (candidate_insns > A64_STATIC_MAX_INSNS)
            candidate_insns = A64_STATIC_MAX_INSNS;
        if (!candidate_insns) break;
        raw_len = candidate_insns * width;
        bytes = cpu->fetch_host + offset;

        entry = &state->cache[cache_index(pc, thumb, cpu->fetch_gen)];
        if (!entry_matches(entry, cpu, bytes, pc, thumb, priv, raw_len))
            decode_entry(state, entry, cpu, bytes, pc, thumb, priv,
                         candidate_insns, raw_len);
        if (!entry->supported) break;
        run_block = &entry->block;
        if (run_block->insn_count > remaining) {
            /* The total chain never crosses its caller/time/device budget.
             * Decode an exact bounded prefix without mutating the cache. */
            if (!decode_longest(bytes, remaining, thumb, pc,
                                &bounded_block))
                break;
            run_block = &bounded_block;
        }

        if (!a64_static_run_read_hits_decoded(cpu, run_block, m->ram,
                                              m->ram_size, &completed)) {
            /* Fail closed, and make a transient contract mismatch re-decode.
             * The decoded runner refuses before changing guest state. */
            invalidate_entry(state, entry);
            break;
        }
        if (!completed) break;
        if (executed_blocks) state->chained_blocks++;
        executed_blocks++;
        retired += completed;
        if (completed != run_block->insn_count) break;
    }

    state->retired += retired;
    return retired;
#else
    (void)m;
    (void)max_insns;
    return 0u;
#endif
}

void s5l8900_static_a64_dispose(s5l8900_t *m) {
    if (!m) return;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    free(m->static_a64_state);
#endif
    m->static_a64_state = NULL;
}
