/*
 * Optional build-time-signed AArch64 execution path for the real SoC loop.
 *
 * This file never emits executable memory. It caches decoded data records and
 * dispatches into ordinary text generated by tools/gen_a64_static.py. The
 * Product memory records consult only arm_cpu's already-proved plain-RAM
 * read/write caches. Direct stores additionally require the frontend's live,
 * separate host_ram_write consent; observers therefore remain fail-closed. A
 * miss performs no access and returns to arm_step(), which remains the sole
 * owner of MMU walks, faults and MMIO. A zero return is always a clean request
 * for the existing arm_step() path.
 */
#include "a64_static_engine.h"

#include <limits.h>
#include <stdlib.h>
#include <string.h>

#if defined(S5LBOX_STATIC_A64_ENGINE)
#include "a64_static.h"

#define STATIC_A64_CACHE_ENTRIES 1024u
#define STATIC_A64_RAW_BYTES (A64_STATIC_MAX_INSNS * 4u)
/* A call observed to retire at most one instruction removes no outer runner
 * entry. Skip fifteen repeats before probing it again: this amortizes the
 * losing path while guaranteeing that a cold graph or changed dynamic path
 * can become eligible without an invalidation signal. */
#define STATIC_A64_REFILL_SINGLE_REPROBE 16u

_Static_assert(S5LBOX_STATIC_A64_PRODUCT_CHAIN_INSNS ==
                   A64_STATIC_MAX_CHAIN_INSNS,
               "product and signed-runner chain ceilings differ");

typedef struct {
    const uint8_t *fetch_host;
    uint32_t pc;
    uint32_t fetch_gen;
    uint8_t raw[STATIC_A64_RAW_BYTES];
    uint8_t raw_len;
    bool fetch_priv;
    bool thumb;
    bool valid;
    bool supported;
    a64_static_block_t block;
} static_a64_entry_t;

typedef struct {
    uint32_t pc;
    uint32_t fetch_gen;
    uint8_t skip_remaining;
    bool fetch_priv;
    bool thumb;
    bool valid;
    bool multi_seen;
} static_a64_refill_predictor_t;

/* One positive privileged compact interval can stop at an instruction that
 * its User-only architectural fallback deliberately leaves untouched.  The
 * outer machine loop used to tick the completed prefix and then enter the
 * native loop again at that same known-losing instruction, producing a zero
 * return before arm_step() finally owned it.  Retain only the exact pending
 * instruction witness needed to bypass that one redundant re-entry after the
 * tick.  This is not a persistent opcode cache: a successful commit consumes
 * it immediately. */
typedef struct {
    const uint8_t *fetch_host;
    uint32_t pc;
    uint32_t fetch_gen;
    uint8_t raw[4];
    uint8_t raw_len;
    bool fetch_priv;
    bool thumb;
    bool valid;
} static_a64_compact_pending_t;

typedef struct {
    uint32_t pc;
    uint32_t insn;
    uint64_t events;
    uint64_t error;
    bool thumb;
    bool privileged;
} static_a64_compact_fallback_hot_t;

typedef struct {
    bool enabled;
    bool persistent;
    bool graph_enabled;
    bool compact_raw_enabled;
    bool compact_raw_privileged_enabled;
    bool compact_raw_window_refill_enabled;
    bool compact_raw_privileged_window_refill_enabled;
    bool compact_raw_window_cache_enabled;
    bool compact_bulk_enabled;
    bool compact_tlb_refill_enabled;
    bool compact_ram_map_enabled;
    arm_ram_map_t *compact_ram_map;
    a64_compact_ram_map_stats_t compact_ram_map_stats;
    arm_ram_window_t compact_ram_window;
    a64_compact_tlb_stats_t compact_tlb_stats;
    bool compact_raw_pc_profile_enabled;
    bool compact_fallback_profile_enabled;
    bool indirect_enabled;
    bool thumb_conditional_enabled;
    bool vstr_enabled;
    bool stm_enabled;
    bool ldm_enabled;
    bool vstm_enabled;
    bool vfp_arithmetic_enabled;
    bool vfp_fp_session_enabled;
    bool fetch_refill_enabled;
    bool known_negative_bypass_enabled;
    unsigned chain_limit;
    uint64_t retired;
    uint64_t chained_blocks;
    uint64_t persistent_chained_blocks;
    uint64_t graph_chained_blocks;
    uint64_t compact_raw_attempts;
    uint64_t compact_raw_calls;
    uint64_t compact_raw_retired;
    uint64_t compact_raw_fallback_retired;
    uint64_t compact_raw_privileged_attempts;
    uint64_t compact_raw_privileged_calls;
    uint64_t compact_raw_privileged_retired;
    uint64_t compact_raw_window_crossings;
    uint64_t compact_raw_window_reloads;
    uint64_t compact_raw_window_stops;
    uint64_t compact_raw_window_fast_refills;
    uint64_t compact_raw_data_refill_attempts;
    uint64_t compact_raw_data_fast_refills;
    uint64_t compact_raw_window_cache_hits;
    uint64_t compact_bulk_calls;
    uint64_t compact_bulk_retired;
    uint64_t compact_raw_privileged_window_refills;
    uint64_t compact_raw_privileged_boundary_retired;
    s5l_static_a64_compact_raw_refusals_t compact_raw_refusals;
    uint64_t fetch_refill_attempts;
    uint64_t fetch_refill_hits;
    uint64_t fetch_refill_skips;
    uint64_t known_negative_bypasses;
    uint64_t compact_fallback_profile_events;
    uint64_t compact_fallback_profile_witness_misses;
    uint64_t compact_fallback_profile_outcome[
        S5L_STATIC_A64_COMPACT_FALLBACK_OUTCOME_COUNT];
    uint64_t compact_fallback_profile_dread_hits;
    uint64_t compact_fallback_profile_dread_misses;
    uint64_t compact_fallback_profile_dwrite_hits;
    uint64_t compact_fallback_profile_dwrite_misses;
    uint64_t compact_fallback_profile_dread_events;
    uint64_t compact_fallback_profile_dwrite_events;
    uint64_t compact_fallback_profile_mixed_data_events;
    uint64_t compact_fallback_profile_no_data_events;
    uint64_t compact_fallback_profile_admitted_data_miss_events;
    uint64_t compact_fallback_profile_admitted_data_tlb_hits;
    uint64_t compact_fallback_profile_admitted_data_tlb_misses;
    uint64_t compact_fallback_profile_admitted_data_tlb_hit_only_events;
    uint64_t compact_fallback_profile_admitted_data_tlb_miss_only_events;
    uint64_t compact_fallback_profile_admitted_data_tlb_mixed_events;
    uint64_t compact_fallback_profile_admitted_data_no_tlb_events;
    static_a64_compact_fallback_hot_t compact_fallback_profile_hot[
        S5L_STATIC_A64_COMPACT_FALLBACK_HOT_COUNT];
    static_a64_entry_t cache[STATIC_A64_CACHE_ENTRIES];
    static_a64_refill_predictor_t
        refill_predictor[STATIC_A64_CACHE_ENTRIES];
    static_a64_compact_pending_t compact_pending;
    a64_static_graph_node_t graph_nodes[A64_STATIC_GRAPH_SLOTS];
} static_a64_state_t;

static static_a64_state_t *static_state(const s5l8900_t *m) {
    return m ? (static_a64_state_t *)m->static_a64_state : NULL;
}

#if defined(S5LBOX_STATIC_A64_ENGINE)
static void compact_profile_counter_add(uint64_t *counter, uint64_t value) {
    if (!counter) return;
    if (UINT64_MAX - *counter < value) *counter = UINT64_MAX;
    else *counter += value;
}

typedef struct {
    uint64_t dread_hits;
    uint64_t dread_misses;
    uint64_t dwrite_hits;
    uint64_t dwrite_misses;
    uint64_t tlb_hits;
    uint64_t tlb_misses;
    bool enabled;
    bool fetch_witness_exact;
    bool admission_supported;
} static_a64_compact_fallback_data_probe_t;

/* The profiler is an explicit diagnostic. Read only a still-live FETCH
 * witness and never refill or translate here: observing a fallback must not
 * make an otherwise unavailable native continuation possible. */
static void compact_fallback_profile_note_current(
        const s5l8900_t *m, static_a64_state_t *state,
        static_a64_compact_fallback_data_probe_t *probe) {
    const arm_cpu_t *cpu;
    uint32_t pc;
    uint32_t fetch_block;
    uint32_t insn;
    unsigned width;
    unsigned offset;
    bool thumb;
    bool privileged;
    a64_compact_raw_admission_t outcome;

    if (probe) memset(probe, 0, sizeof *probe);
    if (!m || !state || !state->compact_fallback_profile_enabled) return;
    compact_profile_counter_add(&state->compact_fallback_profile_events, 1u);
    cpu = &m->cpu;
    if (probe) {
        probe->dread_hits = cpu->dread_hits;
        probe->dread_misses = cpu->dread_misses;
        probe->dwrite_hits = cpu->dwrite_hits;
        probe->dwrite_misses = cpu->dwrite_misses;
        probe->tlb_hits = cpu->tlb_hits;
        probe->tlb_misses = cpu->tlb_misses;
        probe->enabled = true;
    }
    pc = cpu->r[15];
    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    privileged = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    width = thumb ? 2u : 4u;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if ((pc & (width - 1u)) != 0u || !cpu->fetch_host ||
        cpu->fetch_blk != fetch_block || cpu->fetch_gen != cpu->tlb_gen ||
        cpu->fetch_priv != privileged) {
        compact_profile_counter_add(
            &state->compact_fallback_profile_witness_misses, 1u);
        return;
    }
    offset = pc - fetch_block;
    if (offset > UINT32_C(0x400) - width) {
        compact_profile_counter_add(
            &state->compact_fallback_profile_witness_misses, 1u);
        return;
    }
    if (probe) probe->fetch_witness_exact = true;
    insn = (uint32_t)cpu->fetch_host[offset] |
           ((uint32_t)cpu->fetch_host[offset + 1u] << 8);
    if (!thumb) {
        insn |= (uint32_t)cpu->fetch_host[offset + 2u] << 16;
        insn |= (uint32_t)cpu->fetch_host[offset + 3u] << 24;
    }
    outcome = a64_compact_raw_classify_instruction(cpu, insn, thumb);
    if (probe) {
        probe->admission_supported =
            (unsigned)outcome < (unsigned)A64_COMPACT_RAW_ADMITTED_COUNT;
    }
    _Static_assert(A64_COMPACT_RAW_ADMISSION_COUNT ==
                       S5L_STATIC_A64_COMPACT_FALLBACK_OUTCOME_COUNT,
                   "compact fallback outcome count drifted");
    if ((unsigned)outcome <
        S5L_STATIC_A64_COMPACT_FALLBACK_OUTCOME_COUNT) {
        compact_profile_counter_add(
            &state->compact_fallback_profile_outcome[outcome], 1u);
    }

    unsigned empty = S5L_STATIC_A64_COMPACT_FALLBACK_HOT_COUNT;
    unsigned minimum = 0u;
    for (unsigned i = 0u;
         i < S5L_STATIC_A64_COMPACT_FALLBACK_HOT_COUNT; i++) {
        static_a64_compact_fallback_hot_t *hot =
            &state->compact_fallback_profile_hot[i];
        if (hot->events && hot->pc == pc && hot->insn == insn &&
            hot->thumb == thumb && hot->privileged == privileged) {
            compact_profile_counter_add(&hot->events, 1u);
            return;
        }
        if (!hot->events && empty == S5L_STATIC_A64_COMPACT_FALLBACK_HOT_COUNT)
            empty = i;
        if (hot->events <
            state->compact_fallback_profile_hot[minimum].events)
            minimum = i;
    }

    unsigned slot = empty < S5L_STATIC_A64_COMPACT_FALLBACK_HOT_COUNT
        ? empty : minimum;
    static_a64_compact_fallback_hot_t *hot =
        &state->compact_fallback_profile_hot[slot];
    uint64_t prior = hot->events;
    hot->pc = pc;
    hot->insn = insn;
    hot->events = prior == UINT64_MAX ? UINT64_MAX : prior + 1u;
    hot->error = prior;
    hot->thumb = thumb;
    hot->privileged = privileged;
}

static uint64_t compact_profile_counter_delta(uint64_t after,
                                              uint64_t before) {
    /* These counters cannot be reset inside one architectural arm_step().
     * Treat impossible regression as no observation instead of manufacturing
     * a near-UINT64_MAX delta in a diagnostic. */
    return after >= before ? after - before : 0u;
}

static void compact_fallback_profile_note_data(
        const s5l8900_t *m, static_a64_state_t *state,
        const static_a64_compact_fallback_data_probe_t *probe) {
    uint64_t dread_hits;
    uint64_t dread_misses;
    uint64_t dwrite_hits;
    uint64_t dwrite_misses;
    uint64_t tlb_hits;
    uint64_t tlb_misses;
    bool read_event;
    bool write_event;
    bool admitted_data_miss;

    if (!m || !state || !probe || !probe->enabled) return;
    dread_hits = compact_profile_counter_delta(m->cpu.dread_hits,
                                               probe->dread_hits);
    dread_misses = compact_profile_counter_delta(m->cpu.dread_misses,
                                                 probe->dread_misses);
    dwrite_hits = compact_profile_counter_delta(m->cpu.dwrite_hits,
                                                probe->dwrite_hits);
    dwrite_misses = compact_profile_counter_delta(m->cpu.dwrite_misses,
                                                  probe->dwrite_misses);
    tlb_hits = compact_profile_counter_delta(m->cpu.tlb_hits,
                                             probe->tlb_hits);
    tlb_misses = compact_profile_counter_delta(m->cpu.tlb_misses,
                                               probe->tlb_misses);
    compact_profile_counter_add(
        &state->compact_fallback_profile_dread_hits, dread_hits);
    compact_profile_counter_add(
        &state->compact_fallback_profile_dread_misses, dread_misses);
    compact_profile_counter_add(
        &state->compact_fallback_profile_dwrite_hits, dwrite_hits);
    compact_profile_counter_add(
        &state->compact_fallback_profile_dwrite_misses, dwrite_misses);
    read_event = dread_hits != 0u || dread_misses != 0u;
    write_event = dwrite_hits != 0u || dwrite_misses != 0u;
    if (read_event)
        compact_profile_counter_add(
            &state->compact_fallback_profile_dread_events, 1u);
    if (write_event)
        compact_profile_counter_add(
            &state->compact_fallback_profile_dwrite_events, 1u);
    if (read_event && write_event)
        compact_profile_counter_add(
            &state->compact_fallback_profile_mixed_data_events, 1u);
    if (!read_event && !write_event)
        compact_profile_counter_add(
            &state->compact_fallback_profile_no_data_events, 1u);
    admitted_data_miss = probe->fetch_witness_exact &&
        probe->admission_supported &&
        (dread_misses != 0u || dwrite_misses != 0u);
    if (!admitted_data_miss) return;

    compact_profile_counter_add(
        &state->compact_fallback_profile_admitted_data_miss_events, 1u);
    compact_profile_counter_add(
        &state->compact_fallback_profile_admitted_data_tlb_hits, tlb_hits);
    compact_profile_counter_add(
        &state->compact_fallback_profile_admitted_data_tlb_misses,
        tlb_misses);
    if (tlb_hits != 0u && tlb_misses != 0u) {
        compact_profile_counter_add(
            &state->compact_fallback_profile_admitted_data_tlb_mixed_events,
            1u);
    } else if (tlb_hits != 0u) {
        compact_profile_counter_add(
            &state->compact_fallback_profile_admitted_data_tlb_hit_only_events,
            1u);
    } else if (tlb_misses != 0u) {
        compact_profile_counter_add(
            &state->compact_fallback_profile_admitted_data_tlb_miss_only_events,
            1u);
    } else {
        compact_profile_counter_add(
            &state->compact_fallback_profile_admitted_data_no_tlb_events,
            1u);
    }
}
#endif

/* A registered host replacement is a hard block boundary.  Only decode pays
 * this scan: hot graph traversal sees no node at the target and returns to the
 * machine loop, where the hook is invoked once. */
static unsigned cap_before_pre_step_target(const s5l8900_t *m, uint32_t pc,
                                           unsigned width,
                                           unsigned candidate_insns) {
    for (unsigned i = 1u; i < candidate_insns; i++) {
        if (s5l8900_pre_step_target(m, pc + i * width)) return i;
    }
    return candidate_insns;
}

static unsigned cache_index(uint32_t pc, bool thumb, uint32_t generation) {
    uint32_t key = pc >> (thumb ? 1u : 2u);
    key ^= generation * UINT32_C(0x9e3779b1);
    if (thumb) key ^= UINT32_C(0x85ebca6b);
    return key & (STATIC_A64_CACHE_ENTRIES - 1u);
}

static bool compact_pending_capture(s5l8900_t *m,
                                    static_a64_state_t *state) {
    arm_cpu_t *cpu;
    static_a64_compact_pending_t *pending;
    uint32_t pc;
    uint32_t fetch_block;
    unsigned width;
    unsigned offset;
    bool thumb;
    bool priv;

    if (!m || !state || !state->enabled || !state->compact_raw_enabled ||
        !state->known_negative_bypass_enabled || m->pre_step_hook)
        return false;
    cpu = &m->cpu;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    if (!priv) return false;
    pc = cpu->r[15];
    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    width = thumb ? 2u : 4u;
    if ((pc & (width - 1u)) != 0u) return false;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
        cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)
        return false;
    offset = pc - fetch_block;
    if (offset > UINT32_C(0x400) - width) return false;

    pending = &state->compact_pending;
    memset(pending, 0, sizeof *pending);
    pending->fetch_host = cpu->fetch_host;
    pending->pc = pc;
    pending->fetch_gen = cpu->fetch_gen;
    pending->raw_len = (uint8_t)width;
    pending->fetch_priv = priv;
    pending->thumb = thumb;
    memcpy(pending->raw, cpu->fetch_host + offset, width);
    pending->valid = true;
    return true;
}

static bool compact_pending_matches(const s5l8900_t *m,
                                    const static_a64_state_t *state) {
    const arm_cpu_t *cpu;
    const static_a64_compact_pending_t *pending;
    uint32_t pc;
    uint32_t fetch_block;
    unsigned width;
    unsigned offset;
    bool thumb;
    bool priv;

    if (!m || !state || !state->enabled || !state->compact_raw_enabled ||
        !state->known_negative_bypass_enabled || m->pre_step_hook)
        return false;
    pending = &state->compact_pending;
    if (!pending->valid) return false;
    cpu = &m->cpu;
    if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
        !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
        (cpu->cpsr & ARM_CPSR_E) != 0u ||
        (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
        (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
        return false;
    pc = cpu->r[15];
    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    width = thumb ? 2u : 4u;
    if (!priv || (pc & (width - 1u)) != 0u ||
        pending->raw_len != width)
        return false;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
        cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)
        return false;
    offset = pc - fetch_block;
    if (offset > UINT32_C(0x400) - width) return false;
    return pending->fetch_host == cpu->fetch_host && pending->pc == pc &&
           pending->fetch_gen == cpu->fetch_gen &&
           pending->fetch_priv == priv && pending->thumb == thumb &&
           memcmp(pending->raw, cpu->fetch_host + offset, width) == 0;
}

static bool refill_predictor_matches(
    const static_a64_refill_predictor_t *predictor, uint32_t pc,
    uint32_t fetch_gen, bool thumb, bool priv) {
    return predictor->valid && predictor->pc == pc &&
           predictor->fetch_gen == fetch_gen && predictor->thumb == thumb &&
           predictor->fetch_priv == priv;
}

static bool refill_predictor_allows(static_a64_state_t *state, uint32_t pc,
                                    uint32_t fetch_gen, bool thumb,
                                    bool priv) {
    static_a64_refill_predictor_t *predictor =
        &state->refill_predictor[cache_index(pc, thumb, fetch_gen)];
    if (!refill_predictor_matches(predictor, pc, fetch_gen, thumb, priv) ||
        predictor->multi_seen || predictor->skip_remaining == 0u)
        return true;
    predictor->skip_remaining--;
    state->fetch_refill_skips++;
    return false;
}

static void refill_predictor_record(static_a64_state_t *state, uint32_t pc,
                                    uint32_t fetch_gen, bool thumb, bool priv,
                                    unsigned completed, unsigned budget) {
    static_a64_refill_predictor_t *predictor =
        &state->refill_predictor[cache_index(pc, thumb, fetch_gen)];
    if (!refill_predictor_matches(predictor, pc, fetch_gen, thumb, priv)) {
        memset(predictor, 0, sizeof *predictor);
        predictor->pc = pc;
        predictor->fetch_gen = fetch_gen;
        predictor->thumb = thumb;
        predictor->fetch_priv = priv;
        predictor->valid = true;
    }
    if (completed > 1u) {
        predictor->multi_seen = true;
        predictor->skip_remaining = 0u;
    } else if (!predictor->multi_seen && budget > 1u) {
        /* A one-instruction caller/timebase budget says nothing about the
         * natural call length. Leave it due for another probe. */
        predictor->skip_remaining =
            STATIC_A64_REFILL_SINGLE_REPROBE - 1u;
    }
}

static bool entry_matches(const static_a64_entry_t *entry,
                          const arm_cpu_t *cpu, const uint8_t *bytes,
                          uint32_t pc, bool thumb, bool priv,
                          unsigned available_len) {
    return entry->valid && entry->fetch_host == cpu->fetch_host &&
           entry->pc == pc && entry->fetch_gen == cpu->fetch_gen &&
           entry->fetch_priv == priv && entry->thumb == thumb &&
           entry->raw_len != 0u && entry->raw_len <= available_len &&
           memcmp(entry->raw, bytes, entry->raw_len) == 0;
}

/* A negative cache entry is useful only while its complete one-instruction
 * witness and the live fetch identity still match. This is deliberately much
 * narrower than asking whether the next graph node merely says unsupported:
 * self-modifying code or a direct-table alias must get a fresh decode. */
static bool current_cached_unsupported(const s5l8900_t *m,
                                       const static_a64_state_t *state) {
    const arm_cpu_t *cpu;
    const static_a64_entry_t *entry;
    const uint8_t *bytes;
    uint32_t pc;
    uint32_t fetch_block;
    unsigned width;
    unsigned offset;
    unsigned candidate_insns;
    unsigned raw_len;
    bool thumb;
    bool priv;

    if (!m || !state || !state->enabled ||
        !state->known_negative_bypass_enabled)
        return false;
    cpu = &m->cpu;
    if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
        !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
        (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
        (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
        return false;
    pc = cpu->r[15];
    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    width = thumb ? 2u : 4u;
    if ((pc & (width - 1u)) != 0u) return false;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
        cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)
        return false;
    offset = pc - fetch_block;
    candidate_insns = (0x400u - offset) / width;
    if (candidate_insns > A64_STATIC_MAX_INSNS)
        candidate_insns = A64_STATIC_MAX_INSNS;
    if (!candidate_insns) return false;
    raw_len = candidate_insns * width;
    bytes = cpu->fetch_host + offset;
    entry = &state->cache[cache_index(pc, thumb, cpu->fetch_gen)];
    return entry_matches(entry, cpu, bytes, pc, thumb, priv, raw_len) &&
           !entry->supported;
}

static bool decode_longest(const uint8_t *bytes, unsigned candidate_insns,
                           bool thumb, uint32_t pc, bool allow_indirect,
                           bool allow_thumb_conditional, bool allow_vstr,
                           bool allow_stm, bool allow_ldm, bool allow_vstm,
                           bool allow_vfp_arithmetic,
                           a64_static_block_t *out) {
    for (unsigned count = candidate_insns; count != 0u; count--) {
        if (a64_static_decode_memory_hits_bytes_at(bytes, count, thumb, pc,
                                                   out) &&
            (allow_indirect || !out->indirect_exit) &&
            (allow_thumb_conditional || !out->thumb_conditional_exit) &&
            (allow_vstr || !out->vfp_direct_writes) &&
            (allow_stm || !out->stm_direct_writes) &&
            (allow_ldm || !out->ldm_direct_reads) &&
            (allow_vstm || !out->vstm_direct_writes) &&
            (allow_vfp_arithmetic || !out->vfp_arithmetic))
            return true;
    }
    return false;
}

static unsigned graph_index(uint32_t pc, bool thumb) {
    return (pc & UINT32_C(0x3ff)) >> (thumb ? 1u : 2u);
}

static void invalidate_entry(static_a64_state_t *state,
                             static_a64_entry_t *entry) {
    if (!state || !entry) return;
    a64_static_graph_node_t *node =
        &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
    if (node->owner == entry) {
        node->valid = 0u;
        node->supported = 0u;
    }
    entry->valid = false;
}

static void publish_graph_node(static_a64_state_t *state,
                               static_a64_entry_t *entry) {
    a64_static_graph_node_t *node;
    if (!state || !entry) return;
    node = &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
    memset(node, 0, sizeof *node);
    node->owner = entry;
    node->fetch_host = entry->fetch_host;
    node->uops = entry->block.uops;
    node->pc = entry->pc;
    node->fetch_gen = entry->fetch_gen;
    node->insn_count = entry->block.insn_count;
    node->raw_len = entry->raw_len;
    memcpy(node->raw, entry->raw, entry->raw_len);
    node->fetch_priv = entry->fetch_priv ? 1u : 0u;
    node->thumb = entry->thumb ? 1u : 0u;
    node->valid = entry->valid ? 1u : 0u;
    node->supported = entry->supported ? 1u : 0u;
}

static void decode_entry(static_a64_state_t *state, static_a64_entry_t *entry,
                         const arm_cpu_t *cpu,
                         const uint8_t *bytes, uint32_t pc, bool thumb,
                         bool priv, unsigned candidate_insns,
                         unsigned available_len) {
    const unsigned width = thumb ? 2u : 4u;

    invalidate_entry(state, entry);
    memset(entry, 0, sizeof *entry);
    entry->fetch_host = cpu->fetch_host;
    entry->pc = pc;
    entry->fetch_gen = cpu->fetch_gen;
    entry->fetch_priv = priv;
    entry->thumb = thumb;
    entry->valid = true;

    /* Decode the longest exact prefix. Product loads carry a guarded DREAD
     * hit, while a supported terminal store carries a separately consented
     * DWRITE hit. Unsupported forms still shorten to an earlier exact prefix. */
    if (decode_longest(bytes, candidate_insns, thumb, pc,
                       state->indirect_enabled,
                       state->thumb_conditional_enabled,
                       state->vstr_enabled, state->stm_enabled,
                       state->ldm_enabled, state->vstm_enabled,
                       state->vfp_arithmetic_enabled,
                       &entry->block)) {
        entry->supported = true;
        entry->raw_len = (uint8_t)(entry->block.insn_count * width);
    } else {
        /* If instruction zero is unsupported, later bytes cannot make any
         * prefix executable while its own encoding is unchanged. Remembering
         * one instruction therefore detects every semantic change relevant to
         * this negative entry without rescanning the rest of the candidate. */
        entry->raw_len = (uint8_t)width;
    }
    /* A cached supported prefix depends only on the bytes it can execute.
     * Bytes after that prefix may later become supportable; retaining the
     * shorter block is still exact because arm_step() owns the next PC. The
     * old full-candidate witness compared as many as 64 bytes at every hot
     * graph head even when the block contained one instruction. */
    if (entry->raw_len > available_len) {
        invalidate_entry(state, entry);
        return;
    }
    memcpy(entry->raw, bytes, entry->raw_len);
    publish_graph_node(state, entry);
}

typedef struct {
    static_a64_state_t *state;
    s5l8900_t *machine;
    uint32_t fetch_block;
    a64_static_block_t bounded_block;
    static_a64_entry_t *last_entry;
} static_a64_chain_context_t;

static const a64_static_block_t *select_persistent_block(
    static_a64_chain_context_t *context, uint32_t pc, unsigned remaining) {
    s5l8900_t *m;
    arm_cpu_t *cpu;
    uint32_t fetch_block;
    unsigned width;
    unsigned offset;
    unsigned candidate_insns;
    unsigned raw_len;
    bool thumb;
    bool priv;
    const uint8_t *bytes;
    static_a64_entry_t *entry;

    if (!context || !remaining) return NULL;
    m = context->machine;
    cpu = &m->cpu;

    /* Never publish a descriptor for the target itself.  A direct graph link
     * then has no node to cross and the outer machine loop owns the callback. */
    if (s5l8900_pre_step_target(m, pc)) return NULL;

    /* This is the same fail-closed head contract as the legacy C loop. Guest
     * general registers/NZCV remain pinned across this callback, so selection
     * deliberately consults only state that the signed subset cannot mutate. */
    if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
        !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
        (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
        (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
        return NULL;

    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    width = thumb ? 2u : 4u;
    if ((pc & (width - 1u)) != 0u) return NULL;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (fetch_block != context->fetch_block || !cpu->fetch_host ||
        cpu->fetch_blk != fetch_block || cpu->fetch_gen != cpu->tlb_gen ||
        cpu->fetch_priv != priv)
        return NULL;

    offset = pc - fetch_block;
    candidate_insns = (0x400u - offset) / width;
    if (candidate_insns > A64_STATIC_MAX_INSNS)
        candidate_insns = A64_STATIC_MAX_INSNS;
    candidate_insns = cap_before_pre_step_target(
        m, pc, width, candidate_insns);
    if (!candidate_insns) return NULL;
    raw_len = candidate_insns * width;
    bytes = cpu->fetch_host + offset;

    entry = &context->state->cache[
        cache_index(pc, thumb, cpu->fetch_gen)];
    if (!entry_matches(entry, cpu, bytes, pc, thumb, priv, raw_len))
        decode_entry(context->state, entry, cpu, bytes, pc, thumb, priv,
                     candidate_insns, raw_len);
    context->last_entry = entry;
    if (!entry->supported) return NULL;
    if (entry->block.insn_count <= remaining) return &entry->block;

    /* A bounded prefix lives in the persistent invocation's outer C frame;
     * the next callback cannot overwrite it until this block has completed. */
    if (!decode_longest(bytes, remaining, thumb, pc,
                        context->state->indirect_enabled,
                        context->state->thumb_conditional_enabled,
                        context->state->vstr_enabled,
                        context->state->stm_enabled,
                        context->state->ldm_enabled,
                        context->state->vstm_enabled,
                        context->state->vfp_arithmetic_enabled,
                        &context->bounded_block))
        return NULL;
    return &context->bounded_block;
}

static const a64_static_block_t *persistent_next(void *opaque, uint32_t pc,
                                                 unsigned remaining) {
    return select_persistent_block(
        (static_a64_chain_context_t *)opaque, pc, remaining);
}
#endif

bool s5l8900_static_a64_available(void) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    return a64_static_host_available();
#else
    return false;
#endif
}

bool s5l8900_static_a64_is_enabled(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state && state->enabled;
#else
    (void)m;
    return false;
#endif
}

void s5l8900_static_a64_invalidate_derived(s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state) return;
    memset(state->cache, 0, sizeof state->cache);
    memset(&state->compact_pending, 0, sizeof state->compact_pending);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    arm_ram_map_reset(state->compact_ram_map);
    if (state->compact_tlb_refill_enabled || state->compact_ram_map_enabled) {
        /* Reacquire pointer lifetime after a host reset/invalidation. Failure
         * leaves no grant; execution simply uses the existing fallback. */
        (void)arm_ram_window_capture(&state->compact_ram_window, &m->cpu,
                                     m->ram_base, m->ram_size);
    }
#else
    (void)m;
#endif
}

bool s5l8900_static_a64_set_enabled(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) {
            state->enabled = false;
            arm_ram_map_reset(state->compact_ram_map);
        }
        return true;
    }
    if (!a64_static_host_available()) return false;
    if (!state) {
        state = (static_a64_state_t *)calloc(1u, sizeof *state);
        if (!state) return false;
        state->chain_limit = A64_STATIC_MAX_INSNS;
        state->indirect_enabled = true;
        state->thumb_conditional_enabled = true;
        state->vstr_enabled = true;
        state->stm_enabled = true;
        state->ldm_enabled = true;
        state->vstm_enabled = true;
        state->vfp_arithmetic_enabled = true;
        state->vfp_fp_session_enabled = true;
        state->fetch_refill_enabled = true;
        state->known_negative_bypass_enabled = true;
        state->compact_raw_privileged_enabled = true;
        state->compact_raw_window_refill_enabled = true;
        state->compact_raw_privileged_window_refill_enabled = false;
        m->static_a64_state = state;
    }
    state->enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_persistent(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->persistent = false;
        return true;
    }
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->graph_enabled = false;
    state->compact_raw_enabled = false;
    arm_ram_map_reset(state->compact_ram_map);
    state->persistent = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_graph(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->graph_enabled = false;
        return true;
    }
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->persistent = false;
    state->compact_raw_enabled = false;
    arm_ram_map_reset(state->compact_ram_map);
    state->graph_enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_compact_raw(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) {
            state->compact_raw_enabled = false;
            arm_ram_map_reset(state->compact_ram_map);
            memset(&state->compact_pending, 0,
                   sizeof state->compact_pending);
        }
        return true;
    }
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->persistent = false;
    state->graph_enabled = false;
    memset(&state->compact_pending, 0, sizeof state->compact_pending);
    arm_ram_map_reset(state->compact_ram_map);
    state->compact_raw_enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_compact_raw_privileged(s5l8900_t *m,
                                                    bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->compact_raw_privileged_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_compact_raw_window_refill(s5l8900_t *m,
                                                       bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (!enabled && state->compact_ram_map_enabled) return false;
    state->compact_raw_window_refill_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_compact_raw_privileged_window_refill(
        s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->compact_raw_privileged_window_refill_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_compact_raw_window_cache(s5l8900_t *m,
                                                      bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (enabled && state->compact_ram_map_enabled) return false;
    state->compact_raw_window_cache_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_compact_tlb_refill(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !state->compact_raw_enabled ||
        !a64_static_host_available()) return false;
    if (enabled && state->compact_ram_map_enabled) return false;
    state->compact_tlb_refill_enabled = false;
    if (state->compact_ram_map_enabled) return true;
    memset(&state->compact_ram_window, 0, sizeof state->compact_ram_window);
    if (enabled &&
        (!arm_ram_window_capture(&state->compact_ram_window, &m->cpu,
                                  m->ram_base, m->ram_size) ||
         state->compact_ram_window.read_host != m->ram)) return false;
    state->compact_tlb_refill_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_compact_ram_map(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !state->compact_raw_enabled ||
        !a64_static_host_available()) return false;
    if (!enabled) {
        state->compact_ram_map_enabled = false;
        arm_ram_map_reset(state->compact_ram_map);
        return true;
    }
    if (state->compact_tlb_refill_enabled || state->compact_raw_window_cache_enabled ||
        !state->compact_raw_window_refill_enabled)
        return false;
    state->compact_ram_map_enabled = false;
    arm_ram_map_reset(state->compact_ram_map);
    memset(&state->compact_ram_window, 0, sizeof state->compact_ram_window);
    arm_ram_window_t captured;
    if (!arm_ram_window_capture(&captured, &m->cpu, m->ram_base, m->ram_size) ||
        captured.read_host != m->ram) return false;
    if (!state->compact_ram_map) {
        state->compact_ram_map = calloc(1u, sizeof *state->compact_ram_map);
        if (!state->compact_ram_map) return false;
    }
    arm_ram_map_reset(state->compact_ram_map);
    state->compact_ram_window = captured;
    state->compact_ram_map_enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

uint64_t s5l8900_static_a64_compact_ram_map_fetch(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_ram_map_stats.fetch : 0u;
#else
    (void)m;
    return 0u;
#endif
}
uint64_t s5l8900_static_a64_compact_ram_map_read(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_ram_map_stats.read : 0u;
#else
    (void)m;
    return 0u;
#endif
}
uint64_t s5l8900_static_a64_compact_ram_map_write(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_ram_map_stats.write : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_tlb_fetch(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_tlb_stats.fetch : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_tlb_read(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_tlb_stats.read : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_tlb_write(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_tlb_stats.write : 0u;
#else
    (void)m;
    return 0u;
#endif
}

bool s5l8900_static_a64_set_compact_bulk(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !state->compact_raw_enabled ||
        !a64_static_host_available()) return false;
    state->compact_bulk_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

uint64_t s5l8900_static_a64_compact_bulk_calls(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_bulk_calls : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_bulk_retired(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_bulk_retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

bool s5l8900_static_a64_enable_compact_raw_pc_profile(
        s5l8900_t *m, bool fallback_details) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !state->compact_raw_enabled ||
        !a64_static_host_available() ||
        !a64_compact_raw_pc_profile_enable())
        return false;
    state->compact_fallback_profile_events = 0u;
    state->compact_fallback_profile_witness_misses = 0u;
    memset(state->compact_fallback_profile_outcome, 0,
           sizeof state->compact_fallback_profile_outcome);
    state->compact_fallback_profile_dread_hits = 0u;
    state->compact_fallback_profile_dread_misses = 0u;
    state->compact_fallback_profile_dwrite_hits = 0u;
    state->compact_fallback_profile_dwrite_misses = 0u;
    state->compact_fallback_profile_dread_events = 0u;
    state->compact_fallback_profile_dwrite_events = 0u;
    state->compact_fallback_profile_mixed_data_events = 0u;
    state->compact_fallback_profile_no_data_events = 0u;
    state->compact_fallback_profile_admitted_data_miss_events = 0u;
    state->compact_fallback_profile_admitted_data_tlb_hits = 0u;
    state->compact_fallback_profile_admitted_data_tlb_misses = 0u;
    state->compact_fallback_profile_admitted_data_tlb_hit_only_events = 0u;
    state->compact_fallback_profile_admitted_data_tlb_miss_only_events = 0u;
    state->compact_fallback_profile_admitted_data_tlb_mixed_events = 0u;
    state->compact_fallback_profile_admitted_data_no_tlb_events = 0u;
    memset(state->compact_fallback_profile_hot, 0,
           sizeof state->compact_fallback_profile_hot);
    state->compact_raw_pc_profile_enabled = true;
    state->compact_fallback_profile_enabled = fallback_details;
    return true;
#else
    (void)fallback_details;
    return false;
#endif
}

void s5l8900_static_a64_compact_raw_pc_profile(
        const s5l8900_t *m,
        s5l_static_a64_compact_pc_profile_t *out) {
    if (!out) return;
    memset(out, 0, sizeof *out);
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    if (state && state->compact_raw_pc_profile_enabled) {
        a64_compact_raw_pc_profile_t native;
        _Static_assert((unsigned)S5L_STATIC_A64_COMPACT_PC_REGION_COUNT ==
                           (unsigned)A64_COMPACT_RAW_PC_PROFILE_REGION_COUNT,
                       "compact PC-profile region count drifted");
        _Static_assert((unsigned)S5L_STATIC_A64_COMPACT_PC_HOT_COUNT ==
                           (unsigned)A64_COMPACT_RAW_PC_PROFILE_HOT_COUNT,
                       "compact PC-profile hot count drifted");
        _Static_assert((unsigned)S5L_STATIC_A64_COMPACT_PC_GUEST_HOT_COUNT ==
                           (unsigned)A64_COMPACT_RAW_PC_PROFILE_GUEST_HOT_COUNT,
                       "compact PC-profile guest hot count drifted");
        a64_compact_raw_pc_profile_snapshot(&native);
        out->enabled = native.enabled;
        out->polls = native.polls;
        out->not_running = native.not_running;
        out->state_failures = native.state_failures;
        out->target_races = native.target_races;
        out->samples = native.samples;
        out->outside = native.outside;
        for (unsigned i = 0u;
             i < (unsigned)S5L_STATIC_A64_COMPACT_PC_REGION_COUNT; i++)
            out->region[i] = native.region[i];
        out->reference_pc = (uint64_t)native.reference_pc;
        out->outside_pc_captured = native.outside_pc_captured;
        out->outside_pc_dropped = native.outside_pc_dropped;
        for (unsigned i = 0u;
             i < (unsigned)S5L_STATIC_A64_COMPACT_PC_HOT_COUNT; i++) {
            out->outside_hot[i].pc =
                (uint64_t)native.outside_hot[i].pc;
            out->outside_hot[i].samples =
                native.outside_hot[i].samples;
        }
        out->guest_pc_captured = native.guest_pc_captured;
        out->guest_pc_dropped = native.guest_pc_dropped;
        out->guest_pc_unavailable = native.guest_pc_unavailable;
        for (unsigned i = 0u;
             i < (unsigned)S5L_STATIC_A64_COMPACT_PC_GUEST_HOT_COUNT; i++) {
            out->guest_hot[i].pc = (uint64_t)native.guest_hot[i].pc;
            out->guest_hot[i].samples = native.guest_hot[i].samples;
        }
        out->fallback_events = state->compact_fallback_profile_events;
        out->fallback_witness_misses =
            state->compact_fallback_profile_witness_misses;
        memcpy(out->fallback_outcome,
               state->compact_fallback_profile_outcome,
               sizeof out->fallback_outcome);
        out->fallback_dread_hits =
            state->compact_fallback_profile_dread_hits;
        out->fallback_dread_misses =
            state->compact_fallback_profile_dread_misses;
        out->fallback_dwrite_hits =
            state->compact_fallback_profile_dwrite_hits;
        out->fallback_dwrite_misses =
            state->compact_fallback_profile_dwrite_misses;
        out->fallback_dread_events =
            state->compact_fallback_profile_dread_events;
        out->fallback_dwrite_events =
            state->compact_fallback_profile_dwrite_events;
        out->fallback_mixed_data_events =
            state->compact_fallback_profile_mixed_data_events;
        out->fallback_no_data_events =
            state->compact_fallback_profile_no_data_events;
        out->fallback_admitted_data_miss_events =
            state->compact_fallback_profile_admitted_data_miss_events;
        out->fallback_admitted_data_tlb_hits =
            state->compact_fallback_profile_admitted_data_tlb_hits;
        out->fallback_admitted_data_tlb_misses =
            state->compact_fallback_profile_admitted_data_tlb_misses;
        out->fallback_admitted_data_tlb_hit_only_events =
            state->compact_fallback_profile_admitted_data_tlb_hit_only_events;
        out->fallback_admitted_data_tlb_miss_only_events =
            state->compact_fallback_profile_admitted_data_tlb_miss_only_events;
        out->fallback_admitted_data_tlb_mixed_events =
            state->compact_fallback_profile_admitted_data_tlb_mixed_events;
        out->fallback_admitted_data_no_tlb_events =
            state->compact_fallback_profile_admitted_data_no_tlb_events;
        for (unsigned i = 0u;
             i < S5L_STATIC_A64_COMPACT_FALLBACK_HOT_COUNT; i++) {
            out->fallback_hot[i].pc =
                state->compact_fallback_profile_hot[i].pc;
            out->fallback_hot[i].insn =
                state->compact_fallback_profile_hot[i].insn;
            out->fallback_hot[i].events =
                state->compact_fallback_profile_hot[i].events;
            out->fallback_hot[i].error =
                state->compact_fallback_profile_hot[i].error;
            out->fallback_hot[i].thumb =
                state->compact_fallback_profile_hot[i].thumb;
            out->fallback_hot[i].privileged =
                state->compact_fallback_profile_hot[i].privileged;
        }
    }
#else
    (void)m;
#endif
}

bool s5l8900_static_a64_compact_raw_guest_pc_profile_visit(
        const s5l8900_t *m,
        bool (*visit)(void *, uint64_t, uint64_t, uint64_t), void *opaque,
        uint64_t *captured, uint64_t *dropped) {
    if (captured) *captured = 0u;
    if (dropped) *dropped = 0u;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    if (state && state->compact_raw_pc_profile_enabled)
        return a64_compact_raw_guest_pc_profile_visit(
            visit, opaque, captured, dropped);
#else
    (void)m; (void)visit; (void)opaque;
#endif
    return false;
}

bool s5l8900_static_a64_compact_raw_pc_profile_slice_begin(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    if (!state || !state->compact_raw_pc_profile_enabled) return false;
    a64_compact_raw_pc_profile_slice_begin();
    return true;
#else
    (void)m;
    return false;
#endif
}

void s5l8900_static_a64_compact_raw_pc_profile_slice_end(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    if (state && state->compact_raw_pc_profile_enabled)
        a64_compact_raw_pc_profile_slice_end();
#else
    (void)m;
#endif
}

bool s5l8900_static_a64_set_indirect_branches(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->indirect_enabled == enabled) return true;
    /* Entries remember the longest prefix accepted under the old feature
     * set. Clear only derived host state; architectural state and diagnostic
     * counters remain untouched for an exact same-machine A/B. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->indirect_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_thumb_conditional_branches(s5l8900_t *m,
                                                        bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->thumb_conditional_enabled == enabled) return true;
    /* Conditional Thumb exits change the longest exact prefix at a branch
     * head. Invalidate only derived host state for exact same-machine A/B. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->thumb_conditional_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_vstr(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->vstr_enabled == enabled) return true;
    /* VSTR support changes the longest exact prefix at a store head. Clear
     * only derived host state so same-machine off/on experiments cannot reuse
     * a descriptor decoded under the other capability set. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->vstr_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_stm(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->stm_enabled == enabled) return true;
    /* STM support changes the longest exact prefix at a block-store head.
     * Invalidate only derived host state for exact same-machine A/B runs. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->stm_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_ldm(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->ldm_enabled == enabled) return true;
    /* LDM support changes the longest exact prefix at a block-load head.
     * Invalidate only derived host state for exact same-machine A/B runs. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->ldm_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_vstm(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->vstm_enabled == enabled) return true;
    /* VSTM support changes the longest exact prefix at a VFP store head.
     * Invalidate only derived host state for exact same-machine A/B runs. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->vstm_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_vfp_arithmetic(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->vfp_arithmetic_enabled == enabled) return true;
    /* Arithmetic support changes the longest exact prefix at a VFP head.
     * Invalidate only derived state for a same-machine semantic A/B. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->vfp_arithmetic_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_vfp_fp_session(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    /* This is an execution-policy A/B switch. The decoded records and graph
     * are identical; only the generated runner's host-FP save cadence changes. */
    state->vfp_fp_session_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_fetch_refill(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->fetch_refill_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_known_negative_bypass(s5l8900_t *m,
                                                   bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    /* Execution policy only: both arms use identical decoded data and graph
     * nodes, which is required for a meaningful same-binary timing A/B. */
    if (!enabled)
        memset(&state->compact_pending, 0, sizeof state->compact_pending);
    state->known_negative_bypass_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_chain_limit(s5l8900_t *m,
                                        unsigned max_insns) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available() ||
        !max_insns || max_insns > A64_STATIC_MAX_CHAIN_INSNS)
        return false;
    state->chain_limit = max_insns;
    return true;
#else
    (void)max_insns;
    return false;
#endif
}

uint64_t s5l8900_static_a64_retired(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_persistent_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->persistent_chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_graph_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->graph_chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_attempts(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_attempts : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_calls(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_calls : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_retired(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_fallback_retired(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_fallback_retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_privileged_attempts(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_privileged_attempts : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_privileged_calls(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_privileged_calls : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_privileged_retired(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_privileged_retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_window_crossings(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_window_crossings : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_window_reloads(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_window_reloads : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_window_stops(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_window_stops : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_window_fast_refills(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_window_fast_refills : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_data_refill_attempts(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_data_refill_attempts : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_data_fast_refills(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_data_fast_refills : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_window_cache_hits(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_window_cache_hits : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_privileged_window_refills(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_privileged_window_refills : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_privileged_boundary_retired(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_privileged_boundary_retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

void s5l8900_static_a64_compact_raw_refusals(
        const s5l8900_t *m,
        s5l_static_a64_compact_raw_refusals_t *out) {
    if (!out) return;
    memset(out, 0, sizeof *out);
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    if (state) *out = state->compact_raw_refusals;
#else
    (void)m;
#endif
}

uint64_t s5l8900_static_a64_fetch_refill_attempts(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->fetch_refill_attempts : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_fetch_refill_hits(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->fetch_refill_hits : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_fetch_refill_skips(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->fetch_refill_skips : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_known_negative_bypasses(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->known_negative_bypasses : 0u;
#else
    (void)m;
    return 0u;
#endif
}

unsigned s5l8900_static_a64_cached_witness_bytes(const s5l8900_t *m,
                                                 uint32_t pc, bool thumb) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    if (!state) return 0u;
    for (unsigned i = 0u; i < STATIC_A64_CACHE_ENTRIES; i++) {
        const static_a64_entry_t *entry = &state->cache[i];
        if (entry->valid && entry->pc == pc && entry->thumb == thumb)
            return entry->raw_len;
    }
#else
    (void)m;
    (void)pc;
    (void)thumb;
#endif
    return 0u;
}

#if defined(S5LBOX_STATIC_A64_ENGINE)
typedef struct {
    s5l8900_t *machine;
    static_a64_state_t *state;
    arm_status_t status;
    uint32_t fetch_block;
    uint64_t boundary_cycles;
    unsigned budget;
    unsigned boundary_retired;
    s5l8900_static_a64_retirement_boundary_fn retirement_boundary;
    void *retirement_opaque;
} compact_raw_fallback_context_t;

static a64_compact_raw_fallback_result_t compact_raw_fallback(
        void *opaque, a64_compact_raw_code_window_t *next_window,
        const a64_compact_raw_data_miss_t *data_miss) {
    compact_raw_fallback_context_t *context =
        (compact_raw_fallback_context_t *)opaque;
    arm_cpu_t *cpu;
    uint32_t step_block;
    uint32_t next_block;
    uint32_t insn;
    unsigned width;
    unsigned offset;
    bool thumb;
    bool priv;
    bool crossed;
    bool profile_fallback;
    unsigned result;
    static_a64_compact_fallback_data_probe_t data_probe;

    if (!context || !context->machine || !context->state || !next_window)
        return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;
    cpu = &context->machine->cpu;
    step_block = cpu->r[15] & ~UINT32_C(0x3ff);
    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    width = thumb ? 2u : 4u;

    /* The native loop publishes this witness only after an admitted data
     * access misses DREAD/DWRITE and before any architectural mutation. Reuse
     * is deliberately narrower than arm_step(): the PC, invocation TLB
     * generation and access metadata must still match; the fetch window must
     * remain live; and the data block must come from an exact current TLB hit
     * (or MMU-off identity mapping) plus the appropriate host-RAM capability.
     * Any refusal falls through to the literal interpreter, which remains the
     * sole owner of walks, faults, MMIO and write observers. */
    if (data_miss && data_miss->valid == 1u) {
        context->state->compact_raw_data_refill_attempts++;
        if (data_miss->pc == cpu->r[15] &&
            data_miss->tlb_gen == cpu->tlb_gen &&
            data_miss->access <= (uint32_t)ARM_ACCESS_WRITE &&
            data_miss->priv <= 1u &&
            step_block == context->fetch_block &&
            (cpu->r[15] & (width - 1u)) == 0u &&
            arm_fetch_cache_try_refill(cpu, cpu->r[15], priv) &&
            arm_data_cache_try_refill(
                cpu, data_miss->va, (arm_access_t)data_miss->access,
                data_miss->priv != 0u)) {
            next_window->code = cpu->fetch_host;
            next_window->code_base = step_block;
            next_window->code_bytes = UINT32_C(0x400);
            context->state->compact_raw_data_fast_refills++;
            return A64_COMPACT_RAW_FALLBACK_NO_RETIRE_CONTINUE;
        }
    }

    /* A window exit does not itself require an architectural step. User mode
     * can reuse an exact FETCH witness immediately. A privileged prefix first
     * delegates every retirement since the previous continuation to the
     * machine-owned device/clock boundary; only if that gate still admits
     * execution may it prove and publish the next window. The native runner
     * commits its one-cycle-per-retirement counter before this callback, so the
     * cycle delta is the exact prefix length and cannot include an interpreter
     * fallback. Unsupported instructions still stop here: arm_step() remains
     * outside the privileged resident interval and remains the sole owner of
     * walks, faults, MMIO and control-state changes. */
    if (context->state->compact_raw_window_refill_enabled &&
        (!priv ||
         context->state->compact_raw_privileged_window_refill_enabled) &&
        step_block != context->fetch_block &&
        (cpu->r[15] & (width - 1u)) == 0u) {
        unsigned boundary_delta = 0u;
        if (priv) {
            uint64_t retired64;
            if (!context->retirement_boundary)
                return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;
            retired64 = cpu->cycles - context->boundary_cycles;
            if (!retired64 || retired64 > UINT_MAX ||
                retired64 > context->budget - context->boundary_retired)
                return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;
            boundary_delta = (unsigned)retired64;
            bool may_continue = context->retirement_boundary(
                context->retirement_opaque, boundary_delta);
            context->boundary_retired += boundary_delta;
            context->boundary_cycles = cpu->cycles;
            context->state->compact_raw_privileged_boundary_retired +=
                boundary_delta;
            if (!may_continue)
                return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;

            /* The boundary may have sampled a host input, raised an interrupt
             * or invalidated a translation. Re-read every CPU-side admission
             * fact before consuming a pointer. Device refresh cannot change
             * PC or mode, but keeping those checks explicit makes the contract
             * fail closed if that invariant ever changes. */
            thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
            priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
            width = thumb ? 2u : 4u;
            step_block = cpu->r[15] & ~UINT32_C(0x3ff);
            if (!priv || !arm_mode_is_valid(cpu->cpsr) ||
                (cpu->cpsr & ARM_CPSR_E) != 0u || cpu->abort_pending ||
                (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
                (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)) ||
                step_block == context->fetch_block ||
                (cpu->r[15] & (width - 1u)) != 0u)
                return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;
        }
        if (!arm_fetch_cache_try_refill(cpu, cpu->r[15], priv))
            return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;
        offset = cpu->r[15] - step_block;
        insn = (uint32_t)cpu->fetch_host[offset] |
               ((uint32_t)cpu->fetch_host[offset + 1u] << 8);
        if (!thumb) {
            insn |= (uint32_t)cpu->fetch_host[offset + 2u] << 16;
            insn |= (uint32_t)cpu->fetch_host[offset + 3u] << 24;
        }
        if ((unsigned)a64_compact_raw_classify_instruction(cpu, insn, thumb) <
            (unsigned)A64_COMPACT_RAW_ADMITTED_COUNT) {
            next_window->code = cpu->fetch_host;
            next_window->code_base = step_block;
            next_window->code_bytes = UINT32_C(0x400);
            context->state->compact_raw_window_crossings++;
            context->state->compact_raw_window_reloads++;
            context->state->compact_raw_window_fast_refills++;
            if (priv) {
                context->state->compact_raw_privileged_window_refills++;
            }
            context->fetch_block = step_block;
            return A64_COMPACT_RAW_FALLBACK_NO_RETIRE_CONTINUE;
        }
    }

    profile_fallback = context->state->compact_fallback_profile_enabled;
    if (profile_fallback) {
        compact_fallback_profile_note_current(context->machine,
                                              context->state, &data_probe);
    }
    result = s5l8900_static_a64_fallback_step(context->machine,
                                              &context->status);
    if (profile_fallback) {
        compact_fallback_profile_note_data(context->machine, context->state,
                                           &data_probe);
    }
    if (result > A64_COMPACT_RAW_FALLBACK_RETIRE_STOP)
        return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;
    if (result != A64_COMPACT_RAW_FALLBACK_RETIRE_CONTINUE)
        return (a64_compact_raw_fallback_result_t)result;

    next_block = cpu->r[15] & ~UINT32_C(0x3ff);
    crossed = step_block != context->fetch_block ||
              next_block != context->fetch_block;
    if (crossed) context->state->compact_raw_window_crossings++;
    /* This refill consumes only an interpreter-owned live TLB/host-RAM
     * witness. It cannot walk the MMU or enter a fault/device path inside the
     * resident interval; refusal returns to the outer machine loop. */
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    if ((cpu->r[15] & ((cpu->cpsr & ARM_CPSR_T) ? 1u : 3u)) != 0u ||
        !arm_fetch_cache_try_refill(cpu, cpu->r[15], priv)) {
        if (crossed) context->state->compact_raw_window_stops++;
        return A64_COMPACT_RAW_FALLBACK_RETIRE_STOP;
    }

    next_window->code = cpu->fetch_host;
    next_window->code_base = next_block;
    next_window->code_bytes = UINT32_C(0x400);
    if (next_block != context->fetch_block) {
        context->state->compact_raw_window_reloads++;
        context->fetch_block = next_block;
    }
    return A64_COMPACT_RAW_FALLBACK_RETIRE_CONTINUE;
}

static unsigned try_compact_raw(
        s5l8900_t *m, static_a64_state_t *state, unsigned budget,
        arm_status_t *status, bool *known_negative,
        s5l8900_static_a64_retirement_boundary_fn retirement_boundary,
        void *retirement_opaque, unsigned *boundary_retired) {
    arm_cpu_t *cpu = &m->cpu;
    compact_raw_fallback_context_t fallback_context = {
        .machine = m,
        .state = state,
        .status = ARM_OK,
        .fetch_block = 0u,
        .boundary_cycles = m->cpu.cycles,
        .budget = budget,
        .boundary_retired = 0u,
        .retirement_boundary = retirement_boundary,
        .retirement_opaque = retirement_opaque,
    };
    uint32_t fetch_block;
    uint32_t pc;
    unsigned width;
    bool thumb;
    bool priv;
    unsigned completed = 0u;
    unsigned native_completed = 0u;
    unsigned fallback_completed = 0u;
    uint64_t window_cache_hits = 0u;
    a64_compact_bulk_stats_t bulk_stats = {0};
    a64_compact_tlb_stats_t tlb_stats = {0};
    a64_compact_ram_map_stats_t map_stats = {0};

    if (known_negative) *known_negative = false;
    if (boundary_retired) *boundary_retired = 0u;
    memset(&state->compact_pending, 0, sizeof state->compact_pending);
    state->compact_raw_attempts++;
    /* A branch can reach any address in the live 1 KiB window, so a sparse
     * pre-step target list is not enough: any installed host hook disables
     * this path until a target-aware in-loop guard exists. */
    if (!budget || m->pre_step_hook ||
        cpu->arch != ARM_ARCH_V6_ARM1176 ||
        !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
        (cpu->cpsr & ARM_CPSR_E) != 0u ||
        (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
        (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I))) {
        state->compact_raw_refusals.guard++;
        return 0u;
    }
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    if (priv) {
        state->compact_raw_privileged_attempts++;
        if (!state->compact_raw_privileged_enabled) {
            state->compact_raw_refusals.privileged++;
            return 0u;
        }
    }

    pc = cpu->r[15];
    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    width = thumb ? 2u : 4u;
    /* The native loop selects A32/Thumb width from CPSR on every iteration.
     * Requiring A32 alignment here discarded every valid Thumb entry at
     * address 2 modulo 4 before that loop could inspect it. */
    if ((pc & (width - 1u)) != 0u) {
        state->compact_raw_refusals.alignment++;
        return 0u;
    }
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
        cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv) {
        state->compact_raw_refusals.fetch_witness++;
        return 0u;
    }
    fallback_context.fetch_block = fetch_block;
    const arm_ram_window_t *ram_window = &state->compact_ram_window;
    const a64_compact_raw_options_t options = {
        .window_cache_enabled = state->compact_raw_window_cache_enabled,
        .bulk_enabled = state->compact_bulk_enabled,
        .ram_window = (state->compact_tlb_refill_enabled ||
                       state->compact_ram_map_enabled) && !priv &&
            ram_window->read_host == m->ram &&
            ram_window->base == m->ram_base && ram_window->bytes == m->ram_size
                ? ram_window : NULL,
        .owner_fetch_block = &fallback_context.fetch_block,
        .ram_map = state->compact_ram_map_enabled ? state->compact_ram_map : NULL,
        .ram_map_stats = &map_stats,
    };
    if (!a64_compact_raw_run_code_window_resident_options(
            cpu, cpu->fetch_host, fetch_block, UINT32_C(0x400), budget,
            compact_raw_fallback, &fallback_context,
            &options, &window_cache_hits, &bulk_stats, &tlb_stats,
            &completed,
            &native_completed, &fallback_completed)) {
        state->compact_raw_refusals.runner++;
        return 0u;
    }
    if (status) *status = fallback_context.status;
    if (boundary_retired)
        *boundary_retired = fallback_context.boundary_retired;
    state->compact_raw_window_cache_hits += window_cache_hits;
    state->compact_bulk_calls += bulk_stats.calls;
    state->compact_bulk_retired += bulk_stats.retired;
    state->compact_tlb_stats.fetch += tlb_stats.fetch;
    state->compact_tlb_stats.read += tlb_stats.read;
    state->compact_tlb_stats.write += tlb_stats.write;
    state->compact_ram_map_stats.fetch += map_stats.fetch;
    state->compact_ram_map_stats.read += map_stats.read;
    state->compact_ram_map_stats.write += map_stats.write;
    state->compact_raw_window_crossings +=
        window_cache_hits + tlb_stats.fetch + map_stats.fetch;
    state->compact_raw_window_reloads +=
        window_cache_hits + tlb_stats.fetch + map_stats.fetch;
    if (completed) {
        state->compact_raw_calls++;
        state->compact_raw_retired += native_completed;
        state->compact_raw_fallback_retired += fallback_completed;
        if (priv) {
            state->compact_raw_privileged_calls++;
            state->compact_raw_privileged_retired += native_completed;
        }
        state->retired += native_completed;
    } else {
        state->compact_raw_refusals.zero_retired++;
    }
    /* A positive privileged prefix followed by a zero-retirement callback is
     * the exact redundant-entry shape observed on the phone.  Preserve the
     * untouched instruction only until the post-prefix device tick; the
     * machine loop revalidates and consumes it before one literal arm_step().
     * A completed budget did not inspect the next instruction, and a retired
     * fallback is already accounted, so neither may arm the bypass. */
    if (completed && completed < budget && fallback_completed == 0u &&
        fallback_context.status == ARM_OK &&
        compact_pending_capture(m, state) && known_negative)
        *known_negative = true;
    return completed;
}

static unsigned try_persistent(s5l8900_t *m, static_a64_state_t *state,
                               unsigned budget) {
    arm_cpu_t *cpu = &m->cpu;
    static_a64_chain_context_t context = {
        .state = state,
        .machine = m,
        .fetch_block = cpu->r[15] & ~UINT32_C(0x3ff)
    };
    const a64_static_block_t *first =
        select_persistent_block(&context, cpu->r[15], budget);
    unsigned completed = 0u;
    unsigned blocks = 0u;

    if (!first) return 0u;
    if (!a64_static_run_memory_hits_chain(cpu, first, m->ram, m->ram_size,
                                          budget, persistent_next, &context,
                                          state->vfp_fp_session_enabled,
                                          &completed, &blocks)) {
        /* A pre-execution contract mismatch must not become a sticky cache
         * hit. Runtime read/VFP misses are successful exact-prefix returns. */
        if (context.last_entry)
            invalidate_entry(state, context.last_entry);
        return 0u;
    }
    state->retired += completed;
    if (blocks > 1u) {
        state->chained_blocks += blocks - 1u;
        state->persistent_chained_blocks += blocks - 1u;
    }
    return completed;
}

static unsigned try_graph(s5l8900_t *m, static_a64_state_t *state,
                          unsigned budget) {
    arm_cpu_t *cpu = &m->cpu;
    static_a64_chain_context_t context = {
        .state = state,
        .machine = m,
        .fetch_block = cpu->r[15] & ~UINT32_C(0x3ff)
    };
    const a64_static_block_t *first =
        select_persistent_block(&context, cpu->r[15], budget);
    unsigned completed = 0u;
    unsigned blocks = 0u;

    if (!first) return 0u;
    /* The direct table is intentionally scoped by offset, so a descriptor at
     * the same offset in another 1 KiB fetch block may have replaced this
     * cache entry's node. Ensure the C-validated first head is published, but
     * leave an already-owned valid node untouched on the common hot hit. This
     * lets a returning block recover without recopying 128 bytes per entry. */
    {
        static_a64_entry_t *entry = context.last_entry;
        a64_static_graph_node_t *node =
            &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
        if (node->owner != entry || !node->valid || !node->supported)
            publish_graph_node(state, entry);
    }
    if (!a64_static_run_memory_hits_graph(cpu, first, m->ram, m->ram_size,
                                          budget, state->graph_nodes,
                                          state->vfp_fp_session_enabled,
                                          &completed, &blocks)) {
        if (context.last_entry)
            invalidate_entry(state, context.last_entry);
        return 0u;
    }
    state->retired += completed;
    if (blocks > 1u) {
        state->chained_blocks += blocks - 1u;
        state->graph_chained_blocks += blocks - 1u;
    }
    return completed;
}
#endif

unsigned s5l8900_static_a64_try(s5l8900_t *m, unsigned max_insns,
                                bool *known_negative,
                                arm_status_t *status,
                                s5l8900_static_a64_retirement_boundary_fn
                                    retirement_boundary,
                                void *retirement_opaque,
                                unsigned *boundary_retired) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    arm_cpu_t *cpu;
    unsigned budget;
    unsigned retired = 0u;
    unsigned executed_blocks = 0u;
    uint32_t refill_pc = 0u;
    uint32_t refill_gen = 0u;
    bool refill_thumb = false;
    bool refill_priv = false;
    bool refilled = false;

    if (known_negative) *known_negative = false;
    if (status) *status = ARM_OK;
    if (boundary_retired) *boundary_retired = 0u;
    if (!state || !state->enabled || !max_insns ||
        !a64_static_host_available() || !m->ram || !m->ram_size ||
        (m->ram_size & (m->ram_size - 1u)) != 0u)
        return 0u;

    cpu = &m->cpu;
    if (state->fetch_refill_enabled &&
        cpu->arch == ARM_ARCH_V6_ARM1176 &&
        arm_mode_is_valid(cpu->cpsr) && !cpu->abort_pending &&
        !(cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) &&
        !(cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I))) {
        const uint32_t pc = cpu->r[15];
        const bool thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
        const bool priv =
            (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
        const uint32_t fetch_block = pc & ~UINT32_C(0x3ff);
        const unsigned width = thumb ? 2u : 4u;
        if ((pc & (width - 1u)) == 0u &&
            (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
             cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)) {
            if (!refill_predictor_allows(state, pc, cpu->tlb_gen, thumb,
                                         priv))
                return 0u;
            state->fetch_refill_attempts++;
            if (!arm_fetch_cache_try_refill(cpu, pc, priv)) return 0u;
            state->fetch_refill_hits++;
            refill_pc = pc;
            refill_gen = cpu->tlb_gen;
            refill_thumb = thumb;
            refill_priv = priv;
            refilled = true;
        }
    }
    budget = max_insns < state->chain_limit
           ? max_insns : state->chain_limit;
    if (state->compact_raw_enabled) {
        bool compact_known_negative = false;
        unsigned completed = try_compact_raw(
            m, state, budget, status, &compact_known_negative,
            retirement_boundary, retirement_opaque, boundary_retired);
        if (refilled)
            refill_predictor_record(state, refill_pc, refill_gen,
                                    refill_thumb, refill_priv, completed,
                                    budget);
        if (known_negative) *known_negative = compact_known_negative;
        return completed;
    }
    if (state->graph_enabled) {
        unsigned completed = try_graph(m, state, budget);
        if (refilled)
            refill_predictor_record(state, refill_pc, refill_gen,
                                    refill_thumb, refill_priv, completed,
                                    budget);
        if (known_negative && completed && completed < budget &&
            current_cached_unsupported(m, state))
            *known_negative = true;
        return completed;
    }
    if (state->persistent) {
        unsigned completed = try_persistent(m, state, budget);
        if (refilled)
            refill_predictor_record(state, refill_pc, refill_gen,
                                    refill_thumb, refill_priv, completed,
                                    budget);
        if (known_negative && completed && completed < budget &&
            current_cached_unsupported(m, state))
            *known_negative = true;
        return completed;
    }

    while (retired < budget) {
        uint32_t pc;
        uint32_t fetch_block;
        unsigned width;
        unsigned offset;
        unsigned candidate_insns;
        unsigned raw_len;
        unsigned remaining = budget - retired;
        unsigned completed = 0u;
        bool thumb;
        bool priv;
        const uint8_t *bytes;
        static_a64_entry_t *entry;
        a64_static_block_t bounded_block;
        const a64_static_block_t *run_block;

        /* Recheck every head. Signed instructions cannot change the MMU,
         * privilege, interrupt masks or instruction state, but keeping these
         * gates local makes that invariant fail closed if the subset grows. */
        if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
            !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
            (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
            (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
            break;

        pc = cpu->r[15];
        thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
        priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
        width = thumb ? 2u : 4u;
        if ((pc & (width - 1u)) != 0u) break;
        if (s5l8900_pre_step_target(m, pc)) break;

        fetch_block = pc & ~UINT32_C(0x3ff);
        /* A cross-block target must return to arm_step(), which alone owns
         * instruction translation, MMU faults and the new fetch witness. */
        if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
            cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)
            break;

        offset = pc - fetch_block;
        candidate_insns = (0x400u - offset) / width;
        if (candidate_insns > A64_STATIC_MAX_INSNS)
            candidate_insns = A64_STATIC_MAX_INSNS;
        candidate_insns = cap_before_pre_step_target(
            m, pc, width, candidate_insns);
        if (!candidate_insns) break;
        raw_len = candidate_insns * width;
        bytes = cpu->fetch_host + offset;

        entry = &state->cache[cache_index(pc, thumb, cpu->fetch_gen)];
        if (!entry_matches(entry, cpu, bytes, pc, thumb, priv, raw_len))
            decode_entry(state, entry, cpu, bytes, pc, thumb, priv,
                         candidate_insns, raw_len);
        if (!entry->supported) break;
        run_block = &entry->block;
        if (run_block->insn_count > remaining) {
            /* The total chain never crosses its caller/time/device budget.
             * Decode an exact bounded prefix without mutating the cache. */
            if (!decode_longest(bytes, remaining, thumb, pc,
                                state->indirect_enabled,
                                state->thumb_conditional_enabled,
                                state->vstr_enabled,
                                state->stm_enabled, state->ldm_enabled,
                                state->vstm_enabled,
                                state->vfp_arithmetic_enabled,
                                &bounded_block))
                break;
            run_block = &bounded_block;
        }

        if (!a64_static_run_memory_hits_decoded(cpu, run_block, m->ram,
                                                m->ram_size,
                                                state->vfp_fp_session_enabled,
                                                &completed)) {
            /* Fail closed, and make a transient contract mismatch re-decode.
             * The decoded runner refuses before changing guest state. */
            invalidate_entry(state, entry);
            break;
        }
        if (!completed) break;
        if (executed_blocks) state->chained_blocks++;
        executed_blocks++;
        retired += completed;
        if (completed != run_block->insn_count) break;
    }

    state->retired += retired;
    if (refilled)
        refill_predictor_record(state, refill_pc, refill_gen, refill_thumb,
                                refill_priv, retired, budget);
    if (known_negative && retired && retired < budget &&
        current_cached_unsupported(m, state))
        *known_negative = true;
    return retired;
#else
    (void)m;
    (void)max_insns;
    (void)retirement_boundary;
    (void)retirement_opaque;
    if (known_negative) *known_negative = false;
    if (status) *status = ARM_OK;
    if (boundary_retired) *boundary_retired = 0u;
    return 0u;
#endif
}

bool s5l8900_static_a64_commit_known_negative_bypass(s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (state && state->compact_raw_enabled) {
        bool matches = compact_pending_matches(m, state);
        /* Whether the post-tick witness passed or failed, the pending record
         * applies to this boundary only. Never turn it into a sticky opcode
         * exclusion that could hide a later native opportunity. */
        memset(&state->compact_pending, 0, sizeof state->compact_pending);
        if (!matches) return false;
        state->known_negative_bypasses++;
        return true;
    }
    /* The device tick between detection and this call can invalidate fetch or
     * change RAM. Repeat the complete negative witness before skipping work. */
    if (!current_cached_unsupported(m, state)) return false;
    state->known_negative_bypasses++;
    return true;
#else
    (void)m;
    return false;
#endif
}

void s5l8900_static_a64_dispose(s5l8900_t *m) {
    if (!m) return;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (state) free(state->compact_ram_map);
    free(m->static_a64_state);
#endif
    m->static_a64_state = NULL;
}
