/*
 * Optional build-time-signed AArch64 execution path for the real SoC loop.
 *
 * This file never emits executable memory. It caches decoded data records and
 * dispatches into ordinary text generated by tools/gen_a64_static.py. The
 * Product memory records consult only arm_cpu's already-proved plain-RAM
 * read/write caches. Direct stores additionally require the frontend's live,
 * separate host_ram_write consent; observers therefore remain fail-closed. A
 * miss performs no access and returns to arm_step(), which remains the sole
 * owner of MMU walks, faults and MMIO. A zero return is always a clean request
 * for the existing arm_step() path.
 */
#include "a64_static_engine.h"

#include <stdlib.h>
#include <string.h>

#if defined(S5LBOX_STATIC_A64_ENGINE)
#include "a64_static.h"

#define STATIC_A64_CACHE_ENTRIES 1024u
#define STATIC_A64_RAW_BYTES (A64_STATIC_MAX_INSNS * 4u)
/* A call observed to retire at most one instruction removes no outer runner
 * entry. Skip fifteen repeats before probing it again: this amortizes the
 * losing path while guaranteeing that a cold graph or changed dynamic path
 * can become eligible without an invalidation signal. */
#define STATIC_A64_REFILL_SINGLE_REPROBE 16u

_Static_assert(S5LBOX_STATIC_A64_PRODUCT_CHAIN_INSNS ==
                   A64_STATIC_MAX_CHAIN_INSNS,
               "product and signed-runner chain ceilings differ");

typedef struct {
    const uint8_t *fetch_host;
    uint32_t pc;
    uint32_t fetch_gen;
    uint8_t raw[STATIC_A64_RAW_BYTES];
    uint8_t raw_len;
    bool fetch_priv;
    bool thumb;
    bool valid;
    bool supported;
    a64_static_block_t block;
} static_a64_entry_t;

typedef struct {
    uint32_t pc;
    uint32_t fetch_gen;
    uint8_t skip_remaining;
    bool fetch_priv;
    bool thumb;
    bool valid;
    bool multi_seen;
} static_a64_refill_predictor_t;

typedef struct {
    bool enabled;
    bool persistent;
    bool graph_enabled;
    bool compact_raw_enabled;
    bool indirect_enabled;
    bool thumb_conditional_enabled;
    bool vstr_enabled;
    bool stm_enabled;
    bool ldm_enabled;
    bool vstm_enabled;
    bool vfp_arithmetic_enabled;
    bool vfp_fp_session_enabled;
    bool fetch_refill_enabled;
    bool known_negative_bypass_enabled;
    unsigned chain_limit;
    uint64_t retired;
    uint64_t chained_blocks;
    uint64_t persistent_chained_blocks;
    uint64_t graph_chained_blocks;
    uint64_t compact_raw_attempts;
    uint64_t compact_raw_calls;
    uint64_t compact_raw_retired;
    uint64_t compact_raw_fallback_retired;
    uint64_t compact_raw_window_crossings;
    uint64_t compact_raw_window_reloads;
    uint64_t compact_raw_window_stops;
    uint64_t fetch_refill_attempts;
    uint64_t fetch_refill_hits;
    uint64_t fetch_refill_skips;
    uint64_t known_negative_bypasses;
    static_a64_entry_t cache[STATIC_A64_CACHE_ENTRIES];
    static_a64_refill_predictor_t
        refill_predictor[STATIC_A64_CACHE_ENTRIES];
    a64_static_graph_node_t graph_nodes[A64_STATIC_GRAPH_SLOTS];
} static_a64_state_t;

static static_a64_state_t *static_state(const s5l8900_t *m) {
    return m ? (static_a64_state_t *)m->static_a64_state : NULL;
}

/* A registered host replacement is a hard block boundary.  Only decode pays
 * this scan: hot graph traversal sees no node at the target and returns to the
 * machine loop, where the hook is invoked once. */
static unsigned cap_before_pre_step_target(const s5l8900_t *m, uint32_t pc,
                                           unsigned width,
                                           unsigned candidate_insns) {
    for (unsigned i = 1u; i < candidate_insns; i++) {
        if (s5l8900_pre_step_target(m, pc + i * width)) return i;
    }
    return candidate_insns;
}

static unsigned cache_index(uint32_t pc, bool thumb, uint32_t generation) {
    uint32_t key = pc >> (thumb ? 1u : 2u);
    key ^= generation * UINT32_C(0x9e3779b1);
    if (thumb) key ^= UINT32_C(0x85ebca6b);
    return key & (STATIC_A64_CACHE_ENTRIES - 1u);
}

static bool refill_predictor_matches(
    const static_a64_refill_predictor_t *predictor, uint32_t pc,
    uint32_t fetch_gen, bool thumb, bool priv) {
    return predictor->valid && predictor->pc == pc &&
           predictor->fetch_gen == fetch_gen && predictor->thumb == thumb &&
           predictor->fetch_priv == priv;
}

static bool refill_predictor_allows(static_a64_state_t *state, uint32_t pc,
                                    uint32_t fetch_gen, bool thumb,
                                    bool priv) {
    static_a64_refill_predictor_t *predictor =
        &state->refill_predictor[cache_index(pc, thumb, fetch_gen)];
    if (!refill_predictor_matches(predictor, pc, fetch_gen, thumb, priv) ||
        predictor->multi_seen || predictor->skip_remaining == 0u)
        return true;
    predictor->skip_remaining--;
    state->fetch_refill_skips++;
    return false;
}

static void refill_predictor_record(static_a64_state_t *state, uint32_t pc,
                                    uint32_t fetch_gen, bool thumb, bool priv,
                                    unsigned completed, unsigned budget) {
    static_a64_refill_predictor_t *predictor =
        &state->refill_predictor[cache_index(pc, thumb, fetch_gen)];
    if (!refill_predictor_matches(predictor, pc, fetch_gen, thumb, priv)) {
        memset(predictor, 0, sizeof *predictor);
        predictor->pc = pc;
        predictor->fetch_gen = fetch_gen;
        predictor->thumb = thumb;
        predictor->fetch_priv = priv;
        predictor->valid = true;
    }
    if (completed > 1u) {
        predictor->multi_seen = true;
        predictor->skip_remaining = 0u;
    } else if (!predictor->multi_seen && budget > 1u) {
        /* A one-instruction caller/timebase budget says nothing about the
         * natural call length. Leave it due for another probe. */
        predictor->skip_remaining =
            STATIC_A64_REFILL_SINGLE_REPROBE - 1u;
    }
}

static bool entry_matches(const static_a64_entry_t *entry,
                          const arm_cpu_t *cpu, const uint8_t *bytes,
                          uint32_t pc, bool thumb, bool priv,
                          unsigned available_len) {
    return entry->valid && entry->fetch_host == cpu->fetch_host &&
           entry->pc == pc && entry->fetch_gen == cpu->fetch_gen &&
           entry->fetch_priv == priv && entry->thumb == thumb &&
           entry->raw_len != 0u && entry->raw_len <= available_len &&
           memcmp(entry->raw, bytes, entry->raw_len) == 0;
}

/* A negative cache entry is useful only while its complete one-instruction
 * witness and the live fetch identity still match. This is deliberately much
 * narrower than asking whether the next graph node merely says unsupported:
 * self-modifying code or a direct-table alias must get a fresh decode. */
static bool current_cached_unsupported(const s5l8900_t *m,
                                       const static_a64_state_t *state) {
    const arm_cpu_t *cpu;
    const static_a64_entry_t *entry;
    const uint8_t *bytes;
    uint32_t pc;
    uint32_t fetch_block;
    unsigned width;
    unsigned offset;
    unsigned candidate_insns;
    unsigned raw_len;
    bool thumb;
    bool priv;

    if (!m || !state || !state->enabled ||
        !state->known_negative_bypass_enabled)
        return false;
    cpu = &m->cpu;
    if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
        !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
        (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
        (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
        return false;
    pc = cpu->r[15];
    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    width = thumb ? 2u : 4u;
    if ((pc & (width - 1u)) != 0u) return false;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
        cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)
        return false;
    offset = pc - fetch_block;
    candidate_insns = (0x400u - offset) / width;
    if (candidate_insns > A64_STATIC_MAX_INSNS)
        candidate_insns = A64_STATIC_MAX_INSNS;
    if (!candidate_insns) return false;
    raw_len = candidate_insns * width;
    bytes = cpu->fetch_host + offset;
    entry = &state->cache[cache_index(pc, thumb, cpu->fetch_gen)];
    return entry_matches(entry, cpu, bytes, pc, thumb, priv, raw_len) &&
           !entry->supported;
}

static bool decode_longest(const uint8_t *bytes, unsigned candidate_insns,
                           bool thumb, uint32_t pc, bool allow_indirect,
                           bool allow_thumb_conditional, bool allow_vstr,
                           bool allow_stm, bool allow_ldm, bool allow_vstm,
                           bool allow_vfp_arithmetic,
                           a64_static_block_t *out) {
    for (unsigned count = candidate_insns; count != 0u; count--) {
        if (a64_static_decode_memory_hits_bytes_at(bytes, count, thumb, pc,
                                                   out) &&
            (allow_indirect || !out->indirect_exit) &&
            (allow_thumb_conditional || !out->thumb_conditional_exit) &&
            (allow_vstr || !out->vfp_direct_writes) &&
            (allow_stm || !out->stm_direct_writes) &&
            (allow_ldm || !out->ldm_direct_reads) &&
            (allow_vstm || !out->vstm_direct_writes) &&
            (allow_vfp_arithmetic || !out->vfp_arithmetic))
            return true;
    }
    return false;
}

static unsigned graph_index(uint32_t pc, bool thumb) {
    return (pc & UINT32_C(0x3ff)) >> (thumb ? 1u : 2u);
}

static void invalidate_entry(static_a64_state_t *state,
                             static_a64_entry_t *entry) {
    if (!state || !entry) return;
    a64_static_graph_node_t *node =
        &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
    if (node->owner == entry) {
        node->valid = 0u;
        node->supported = 0u;
    }
    entry->valid = false;
}

static void publish_graph_node(static_a64_state_t *state,
                               static_a64_entry_t *entry) {
    a64_static_graph_node_t *node;
    if (!state || !entry) return;
    node = &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
    memset(node, 0, sizeof *node);
    node->owner = entry;
    node->fetch_host = entry->fetch_host;
    node->uops = entry->block.uops;
    node->pc = entry->pc;
    node->fetch_gen = entry->fetch_gen;
    node->insn_count = entry->block.insn_count;
    node->raw_len = entry->raw_len;
    memcpy(node->raw, entry->raw, entry->raw_len);
    node->fetch_priv = entry->fetch_priv ? 1u : 0u;
    node->thumb = entry->thumb ? 1u : 0u;
    node->valid = entry->valid ? 1u : 0u;
    node->supported = entry->supported ? 1u : 0u;
}

static void decode_entry(static_a64_state_t *state, static_a64_entry_t *entry,
                         const arm_cpu_t *cpu,
                         const uint8_t *bytes, uint32_t pc, bool thumb,
                         bool priv, unsigned candidate_insns,
                         unsigned available_len) {
    const unsigned width = thumb ? 2u : 4u;

    invalidate_entry(state, entry);
    memset(entry, 0, sizeof *entry);
    entry->fetch_host = cpu->fetch_host;
    entry->pc = pc;
    entry->fetch_gen = cpu->fetch_gen;
    entry->fetch_priv = priv;
    entry->thumb = thumb;
    entry->valid = true;

    /* Decode the longest exact prefix. Product loads carry a guarded DREAD
     * hit, while a supported terminal store carries a separately consented
     * DWRITE hit. Unsupported forms still shorten to an earlier exact prefix. */
    if (decode_longest(bytes, candidate_insns, thumb, pc,
                       state->indirect_enabled,
                       state->thumb_conditional_enabled,
                       state->vstr_enabled, state->stm_enabled,
                       state->ldm_enabled, state->vstm_enabled,
                       state->vfp_arithmetic_enabled,
                       &entry->block)) {
        entry->supported = true;
        entry->raw_len = (uint8_t)(entry->block.insn_count * width);
    } else {
        /* If instruction zero is unsupported, later bytes cannot make any
         * prefix executable while its own encoding is unchanged. Remembering
         * one instruction therefore detects every semantic change relevant to
         * this negative entry without rescanning the rest of the candidate. */
        entry->raw_len = (uint8_t)width;
    }
    /* A cached supported prefix depends only on the bytes it can execute.
     * Bytes after that prefix may later become supportable; retaining the
     * shorter block is still exact because arm_step() owns the next PC. The
     * old full-candidate witness compared as many as 64 bytes at every hot
     * graph head even when the block contained one instruction. */
    if (entry->raw_len > available_len) {
        invalidate_entry(state, entry);
        return;
    }
    memcpy(entry->raw, bytes, entry->raw_len);
    publish_graph_node(state, entry);
}

typedef struct {
    static_a64_state_t *state;
    s5l8900_t *machine;
    uint32_t fetch_block;
    a64_static_block_t bounded_block;
    static_a64_entry_t *last_entry;
} static_a64_chain_context_t;

static const a64_static_block_t *select_persistent_block(
    static_a64_chain_context_t *context, uint32_t pc, unsigned remaining) {
    s5l8900_t *m;
    arm_cpu_t *cpu;
    uint32_t fetch_block;
    unsigned width;
    unsigned offset;
    unsigned candidate_insns;
    unsigned raw_len;
    bool thumb;
    bool priv;
    const uint8_t *bytes;
    static_a64_entry_t *entry;

    if (!context || !remaining) return NULL;
    m = context->machine;
    cpu = &m->cpu;

    /* Never publish a descriptor for the target itself.  A direct graph link
     * then has no node to cross and the outer machine loop owns the callback. */
    if (s5l8900_pre_step_target(m, pc)) return NULL;

    /* This is the same fail-closed head contract as the legacy C loop. Guest
     * general registers/NZCV remain pinned across this callback, so selection
     * deliberately consults only state that the signed subset cannot mutate. */
    if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
        !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
        (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
        (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
        return NULL;

    thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    width = thumb ? 2u : 4u;
    if ((pc & (width - 1u)) != 0u) return NULL;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (fetch_block != context->fetch_block || !cpu->fetch_host ||
        cpu->fetch_blk != fetch_block || cpu->fetch_gen != cpu->tlb_gen ||
        cpu->fetch_priv != priv)
        return NULL;

    offset = pc - fetch_block;
    candidate_insns = (0x400u - offset) / width;
    if (candidate_insns > A64_STATIC_MAX_INSNS)
        candidate_insns = A64_STATIC_MAX_INSNS;
    candidate_insns = cap_before_pre_step_target(
        m, pc, width, candidate_insns);
    if (!candidate_insns) return NULL;
    raw_len = candidate_insns * width;
    bytes = cpu->fetch_host + offset;

    entry = &context->state->cache[
        cache_index(pc, thumb, cpu->fetch_gen)];
    if (!entry_matches(entry, cpu, bytes, pc, thumb, priv, raw_len))
        decode_entry(context->state, entry, cpu, bytes, pc, thumb, priv,
                     candidate_insns, raw_len);
    context->last_entry = entry;
    if (!entry->supported) return NULL;
    if (entry->block.insn_count <= remaining) return &entry->block;

    /* A bounded prefix lives in the persistent invocation's outer C frame;
     * the next callback cannot overwrite it until this block has completed. */
    if (!decode_longest(bytes, remaining, thumb, pc,
                        context->state->indirect_enabled,
                        context->state->thumb_conditional_enabled,
                        context->state->vstr_enabled,
                        context->state->stm_enabled,
                        context->state->ldm_enabled,
                        context->state->vstm_enabled,
                        context->state->vfp_arithmetic_enabled,
                        &context->bounded_block))
        return NULL;
    return &context->bounded_block;
}

static const a64_static_block_t *persistent_next(void *opaque, uint32_t pc,
                                                 unsigned remaining) {
    return select_persistent_block(
        (static_a64_chain_context_t *)opaque, pc, remaining);
}
#endif

bool s5l8900_static_a64_available(void) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    return a64_static_host_available();
#else
    return false;
#endif
}

bool s5l8900_static_a64_is_enabled(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state && state->enabled;
#else
    (void)m;
    return false;
#endif
}

void s5l8900_static_a64_invalidate_derived(s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state) return;
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
#else
    (void)m;
#endif
}

bool s5l8900_static_a64_set_enabled(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->enabled = false;
        return true;
    }
    if (!a64_static_host_available()) return false;
    if (!state) {
        state = (static_a64_state_t *)calloc(1u, sizeof *state);
        if (!state) return false;
        state->chain_limit = A64_STATIC_MAX_INSNS;
        state->indirect_enabled = true;
        state->thumb_conditional_enabled = true;
        state->vstr_enabled = true;
        state->stm_enabled = true;
        state->ldm_enabled = true;
        state->vstm_enabled = true;
        state->vfp_arithmetic_enabled = true;
        state->vfp_fp_session_enabled = true;
        state->fetch_refill_enabled = true;
        state->known_negative_bypass_enabled = true;
        m->static_a64_state = state;
    }
    state->enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_persistent(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->persistent = false;
        return true;
    }
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->graph_enabled = false;
    state->compact_raw_enabled = false;
    state->persistent = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_graph(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->graph_enabled = false;
        return true;
    }
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->persistent = false;
    state->compact_raw_enabled = false;
    state->graph_enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_compact_raw(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!enabled) {
        if (state) state->compact_raw_enabled = false;
        return true;
    }
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->persistent = false;
    state->graph_enabled = false;
    state->compact_raw_enabled = true;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_indirect_branches(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->indirect_enabled == enabled) return true;
    /* Entries remember the longest prefix accepted under the old feature
     * set. Clear only derived host state; architectural state and diagnostic
     * counters remain untouched for an exact same-machine A/B. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->indirect_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_thumb_conditional_branches(s5l8900_t *m,
                                                        bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->thumb_conditional_enabled == enabled) return true;
    /* Conditional Thumb exits change the longest exact prefix at a branch
     * head. Invalidate only derived host state for exact same-machine A/B. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->thumb_conditional_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_vstr(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->vstr_enabled == enabled) return true;
    /* VSTR support changes the longest exact prefix at a store head. Clear
     * only derived host state so same-machine off/on experiments cannot reuse
     * a descriptor decoded under the other capability set. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->vstr_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_stm(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->stm_enabled == enabled) return true;
    /* STM support changes the longest exact prefix at a block-store head.
     * Invalidate only derived host state for exact same-machine A/B runs. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->stm_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_ldm(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->ldm_enabled == enabled) return true;
    /* LDM support changes the longest exact prefix at a block-load head.
     * Invalidate only derived host state for exact same-machine A/B runs. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->ldm_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_vstm(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->vstm_enabled == enabled) return true;
    /* VSTM support changes the longest exact prefix at a VFP store head.
     * Invalidate only derived host state for exact same-machine A/B runs. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->vstm_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_vfp_arithmetic(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    if (state->vfp_arithmetic_enabled == enabled) return true;
    /* Arithmetic support changes the longest exact prefix at a VFP head.
     * Invalidate only derived state for a same-machine semantic A/B. */
    memset(state->cache, 0, sizeof state->cache);
    memset(state->graph_nodes, 0, sizeof state->graph_nodes);
    state->vfp_arithmetic_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_vfp_fp_session(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    /* This is an execution-policy A/B switch. The decoded records and graph
     * are identical; only the generated runner's host-FP save cadence changes. */
    state->vfp_fp_session_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_fetch_refill(s5l8900_t *m, bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    state->fetch_refill_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_known_negative_bypass(s5l8900_t *m,
                                                   bool enabled) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available())
        return false;
    /* Execution policy only: both arms use identical decoded data and graph
     * nodes, which is required for a meaningful same-binary timing A/B. */
    state->known_negative_bypass_enabled = enabled;
    return true;
#else
    (void)enabled;
    return false;
#endif
}

bool s5l8900_static_a64_set_chain_limit(s5l8900_t *m,
                                        unsigned max_insns) {
    if (!m) return false;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    if (!state || !state->enabled || !a64_static_host_available() ||
        !max_insns || max_insns > A64_STATIC_MAX_CHAIN_INSNS)
        return false;
    state->chain_limit = max_insns;
    return true;
#else
    (void)max_insns;
    return false;
#endif
}

uint64_t s5l8900_static_a64_retired(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_persistent_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->persistent_chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_graph_chained_blocks(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->graph_chained_blocks : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_attempts(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_attempts : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_calls(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_calls : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_retired(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_fallback_retired(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_fallback_retired : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_window_crossings(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_window_crossings : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_window_reloads(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_window_reloads : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_compact_raw_window_stops(
        const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->compact_raw_window_stops : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_fetch_refill_attempts(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->fetch_refill_attempts : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_fetch_refill_hits(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->fetch_refill_hits : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_fetch_refill_skips(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->fetch_refill_skips : 0u;
#else
    (void)m;
    return 0u;
#endif
}

uint64_t s5l8900_static_a64_known_negative_bypasses(const s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    return state ? state->known_negative_bypasses : 0u;
#else
    (void)m;
    return 0u;
#endif
}

unsigned s5l8900_static_a64_cached_witness_bytes(const s5l8900_t *m,
                                                 uint32_t pc, bool thumb) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    const static_a64_state_t *state = static_state(m);
    if (!state) return 0u;
    for (unsigned i = 0u; i < STATIC_A64_CACHE_ENTRIES; i++) {
        const static_a64_entry_t *entry = &state->cache[i];
        if (entry->valid && entry->pc == pc && entry->thumb == thumb)
            return entry->raw_len;
    }
#else
    (void)m;
    (void)pc;
    (void)thumb;
#endif
    return 0u;
}

#if defined(S5LBOX_STATIC_A64_ENGINE)
typedef struct {
    s5l8900_t *machine;
    static_a64_state_t *state;
    arm_status_t status;
    uint32_t fetch_block;
} compact_raw_fallback_context_t;

static a64_compact_raw_fallback_result_t compact_raw_fallback(
        void *opaque, a64_compact_raw_code_window_t *next_window) {
    compact_raw_fallback_context_t *context =
        (compact_raw_fallback_context_t *)opaque;
    arm_cpu_t *cpu;
    uint32_t step_block;
    uint32_t next_block;
    bool crossed;
    unsigned result;

    if (!context || !context->machine || !context->state || !next_window)
        return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;
    cpu = &context->machine->cpu;
    step_block = cpu->r[15] & ~UINT32_C(0x3ff);
    result = s5l8900_static_a64_fallback_step(context->machine,
                                              &context->status);
    if (result > A64_COMPACT_RAW_FALLBACK_RETIRE_STOP)
        return A64_COMPACT_RAW_FALLBACK_NO_RETIRE;
    if (result != A64_COMPACT_RAW_FALLBACK_RETIRE_CONTINUE)
        return (a64_compact_raw_fallback_result_t)result;

    next_block = cpu->r[15] & ~UINT32_C(0x3ff);
    crossed = step_block != context->fetch_block ||
              next_block != context->fetch_block;
    if (crossed) context->state->compact_raw_window_crossings++;
    /* This refill consumes only an interpreter-owned live TLB/host-RAM
     * witness. It cannot walk the MMU or enter a fault/device path inside the
     * resident interval; refusal returns to the outer machine loop. */
    if ((cpu->r[15] & ((cpu->cpsr & ARM_CPSR_T) ? 1u : 3u)) != 0u ||
        !arm_fetch_cache_try_refill(cpu, cpu->r[15], false)) {
        if (crossed) context->state->compact_raw_window_stops++;
        return A64_COMPACT_RAW_FALLBACK_RETIRE_STOP;
    }

    next_window->code = cpu->fetch_host;
    next_window->code_base = next_block;
    next_window->code_bytes = UINT32_C(0x400);
    if (next_block != context->fetch_block) {
        context->state->compact_raw_window_reloads++;
        context->fetch_block = next_block;
    }
    return A64_COMPACT_RAW_FALLBACK_RETIRE_CONTINUE;
}

static unsigned try_compact_raw(s5l8900_t *m, static_a64_state_t *state,
                                unsigned budget, arm_status_t *status) {
    arm_cpu_t *cpu = &m->cpu;
    compact_raw_fallback_context_t fallback_context = {
        .machine = m,
        .state = state,
        .status = ARM_OK,
        .fetch_block = 0u,
    };
    uint32_t fetch_block;
    uint32_t pc;
    bool priv;
    unsigned completed = 0u;
    unsigned native_completed = 0u;
    unsigned fallback_completed = 0u;

    state->compact_raw_attempts++;
    /* A branch can reach any address in the live 1 KiB window, so a sparse
     * pre-step target list is not enough: any installed host hook disables
     * this path until a target-aware in-loop guard exists. */
    if (!budget || m->pre_step_hook ||
        cpu->arch != ARM_ARCH_V6_ARM1176 ||
        !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
        (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR ||
        (cpu->cpsr & ARM_CPSR_E) != 0u ||
        (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
        (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
        return 0u;

    pc = cpu->r[15];
    if ((pc & 3u) != 0u) return 0u;
    priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
    fetch_block = pc & ~UINT32_C(0x3ff);
    if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
        cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)
        return 0u;
    fallback_context.fetch_block = fetch_block;
    if (!a64_compact_raw_run_code_window_resident(
            cpu, cpu->fetch_host, fetch_block, UINT32_C(0x400), budget,
            compact_raw_fallback, &fallback_context, &completed,
            &native_completed, &fallback_completed))
        return 0u;
    if (status) *status = fallback_context.status;
    if (completed) {
        state->compact_raw_calls++;
        state->compact_raw_retired += native_completed;
        state->compact_raw_fallback_retired += fallback_completed;
        state->retired += native_completed;
    }
    return completed;
}

static unsigned try_persistent(s5l8900_t *m, static_a64_state_t *state,
                               unsigned budget) {
    arm_cpu_t *cpu = &m->cpu;
    static_a64_chain_context_t context = {
        .state = state,
        .machine = m,
        .fetch_block = cpu->r[15] & ~UINT32_C(0x3ff)
    };
    const a64_static_block_t *first =
        select_persistent_block(&context, cpu->r[15], budget);
    unsigned completed = 0u;
    unsigned blocks = 0u;

    if (!first) return 0u;
    if (!a64_static_run_memory_hits_chain(cpu, first, m->ram, m->ram_size,
                                          budget, persistent_next, &context,
                                          state->vfp_fp_session_enabled,
                                          &completed, &blocks)) {
        /* A pre-execution contract mismatch must not become a sticky cache
         * hit. Runtime read/VFP misses are successful exact-prefix returns. */
        if (context.last_entry)
            invalidate_entry(state, context.last_entry);
        return 0u;
    }
    state->retired += completed;
    if (blocks > 1u) {
        state->chained_blocks += blocks - 1u;
        state->persistent_chained_blocks += blocks - 1u;
    }
    return completed;
}

static unsigned try_graph(s5l8900_t *m, static_a64_state_t *state,
                          unsigned budget) {
    arm_cpu_t *cpu = &m->cpu;
    static_a64_chain_context_t context = {
        .state = state,
        .machine = m,
        .fetch_block = cpu->r[15] & ~UINT32_C(0x3ff)
    };
    const a64_static_block_t *first =
        select_persistent_block(&context, cpu->r[15], budget);
    unsigned completed = 0u;
    unsigned blocks = 0u;

    if (!first) return 0u;
    /* The direct table is intentionally scoped by offset, so a descriptor at
     * the same offset in another 1 KiB fetch block may have replaced this
     * cache entry's node. Ensure the C-validated first head is published, but
     * leave an already-owned valid node untouched on the common hot hit. This
     * lets a returning block recover without recopying 128 bytes per entry. */
    {
        static_a64_entry_t *entry = context.last_entry;
        a64_static_graph_node_t *node =
            &state->graph_nodes[graph_index(entry->pc, entry->thumb)];
        if (node->owner != entry || !node->valid || !node->supported)
            publish_graph_node(state, entry);
    }
    if (!a64_static_run_memory_hits_graph(cpu, first, m->ram, m->ram_size,
                                          budget, state->graph_nodes,
                                          state->vfp_fp_session_enabled,
                                          &completed, &blocks)) {
        if (context.last_entry)
            invalidate_entry(state, context.last_entry);
        return 0u;
    }
    state->retired += completed;
    if (blocks > 1u) {
        state->chained_blocks += blocks - 1u;
        state->graph_chained_blocks += blocks - 1u;
    }
    return completed;
}
#endif

unsigned s5l8900_static_a64_try(s5l8900_t *m, unsigned max_insns,
                                bool *known_negative,
                                arm_status_t *status) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    arm_cpu_t *cpu;
    unsigned budget;
    unsigned retired = 0u;
    unsigned executed_blocks = 0u;
    uint32_t refill_pc = 0u;
    uint32_t refill_gen = 0u;
    bool refill_thumb = false;
    bool refill_priv = false;
    bool refilled = false;

    if (known_negative) *known_negative = false;
    if (status) *status = ARM_OK;
    if (!state || !state->enabled || !max_insns ||
        !a64_static_host_available() || !m->ram || !m->ram_size ||
        (m->ram_size & (m->ram_size - 1u)) != 0u)
        return 0u;

    cpu = &m->cpu;
    if (state->fetch_refill_enabled &&
        cpu->arch == ARM_ARCH_V6_ARM1176 &&
        arm_mode_is_valid(cpu->cpsr) && !cpu->abort_pending &&
        !(cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) &&
        !(cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I))) {
        const uint32_t pc = cpu->r[15];
        const bool thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
        const bool priv =
            (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
        const uint32_t fetch_block = pc & ~UINT32_C(0x3ff);
        const unsigned width = thumb ? 2u : 4u;
        if ((pc & (width - 1u)) == 0u &&
            (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
             cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)) {
            if (!refill_predictor_allows(state, pc, cpu->tlb_gen, thumb,
                                         priv))
                return 0u;
            state->fetch_refill_attempts++;
            if (!arm_fetch_cache_try_refill(cpu, pc, priv)) return 0u;
            state->fetch_refill_hits++;
            refill_pc = pc;
            refill_gen = cpu->tlb_gen;
            refill_thumb = thumb;
            refill_priv = priv;
            refilled = true;
        }
    }
    budget = max_insns < state->chain_limit
           ? max_insns : state->chain_limit;
    if (state->compact_raw_enabled) {
        unsigned completed = try_compact_raw(m, state, budget, status);
        if (refilled)
            refill_predictor_record(state, refill_pc, refill_gen,
                                    refill_thumb, refill_priv, completed,
                                    budget);
        return completed;
    }
    if (state->graph_enabled) {
        unsigned completed = try_graph(m, state, budget);
        if (refilled)
            refill_predictor_record(state, refill_pc, refill_gen,
                                    refill_thumb, refill_priv, completed,
                                    budget);
        if (known_negative && completed && completed < budget &&
            current_cached_unsupported(m, state))
            *known_negative = true;
        return completed;
    }
    if (state->persistent) {
        unsigned completed = try_persistent(m, state, budget);
        if (refilled)
            refill_predictor_record(state, refill_pc, refill_gen,
                                    refill_thumb, refill_priv, completed,
                                    budget);
        if (known_negative && completed && completed < budget &&
            current_cached_unsupported(m, state))
            *known_negative = true;
        return completed;
    }

    while (retired < budget) {
        uint32_t pc;
        uint32_t fetch_block;
        unsigned width;
        unsigned offset;
        unsigned candidate_insns;
        unsigned raw_len;
        unsigned remaining = budget - retired;
        unsigned completed = 0u;
        bool thumb;
        bool priv;
        const uint8_t *bytes;
        static_a64_entry_t *entry;
        a64_static_block_t bounded_block;
        const a64_static_block_t *run_block;

        /* Recheck every head. Signed instructions cannot change the MMU,
         * privilege, interrupt masks or instruction state, but keeping these
         * gates local makes that invariant fail closed if the subset grows. */
        if (cpu->arch != ARM_ARCH_V6_ARM1176 ||
            !arm_mode_is_valid(cpu->cpsr) || cpu->abort_pending ||
            (cpu->fiq_line && !(cpu->cpsr & ARM_CPSR_F)) ||
            (cpu->irq_line && !(cpu->cpsr & ARM_CPSR_I)))
            break;

        pc = cpu->r[15];
        thumb = (cpu->cpsr & ARM_CPSR_T) != 0u;
        priv = (cpu->cpsr & ARM_CPSR_MODE_MASK) != ARM_MODE_USR;
        width = thumb ? 2u : 4u;
        if ((pc & (width - 1u)) != 0u) break;
        if (s5l8900_pre_step_target(m, pc)) break;

        fetch_block = pc & ~UINT32_C(0x3ff);
        /* A cross-block target must return to arm_step(), which alone owns
         * instruction translation, MMU faults and the new fetch witness. */
        if (!cpu->fetch_host || cpu->fetch_blk != fetch_block ||
            cpu->fetch_gen != cpu->tlb_gen || cpu->fetch_priv != priv)
            break;

        offset = pc - fetch_block;
        candidate_insns = (0x400u - offset) / width;
        if (candidate_insns > A64_STATIC_MAX_INSNS)
            candidate_insns = A64_STATIC_MAX_INSNS;
        candidate_insns = cap_before_pre_step_target(
            m, pc, width, candidate_insns);
        if (!candidate_insns) break;
        raw_len = candidate_insns * width;
        bytes = cpu->fetch_host + offset;

        entry = &state->cache[cache_index(pc, thumb, cpu->fetch_gen)];
        if (!entry_matches(entry, cpu, bytes, pc, thumb, priv, raw_len))
            decode_entry(state, entry, cpu, bytes, pc, thumb, priv,
                         candidate_insns, raw_len);
        if (!entry->supported) break;
        run_block = &entry->block;
        if (run_block->insn_count > remaining) {
            /* The total chain never crosses its caller/time/device budget.
             * Decode an exact bounded prefix without mutating the cache. */
            if (!decode_longest(bytes, remaining, thumb, pc,
                                state->indirect_enabled,
                                state->thumb_conditional_enabled,
                                state->vstr_enabled,
                                state->stm_enabled, state->ldm_enabled,
                                state->vstm_enabled,
                                state->vfp_arithmetic_enabled,
                                &bounded_block))
                break;
            run_block = &bounded_block;
        }

        if (!a64_static_run_memory_hits_decoded(cpu, run_block, m->ram,
                                                m->ram_size,
                                                state->vfp_fp_session_enabled,
                                                &completed)) {
            /* Fail closed, and make a transient contract mismatch re-decode.
             * The decoded runner refuses before changing guest state. */
            invalidate_entry(state, entry);
            break;
        }
        if (!completed) break;
        if (executed_blocks) state->chained_blocks++;
        executed_blocks++;
        retired += completed;
        if (completed != run_block->insn_count) break;
    }

    state->retired += retired;
    if (refilled)
        refill_predictor_record(state, refill_pc, refill_gen, refill_thumb,
                                refill_priv, retired, budget);
    if (known_negative && retired && retired < budget &&
        current_cached_unsupported(m, state))
        *known_negative = true;
    return retired;
#else
    (void)m;
    (void)max_insns;
    if (known_negative) *known_negative = false;
    if (status) *status = ARM_OK;
    return 0u;
#endif
}

bool s5l8900_static_a64_commit_known_negative_bypass(s5l8900_t *m) {
#if defined(S5LBOX_STATIC_A64_ENGINE)
    static_a64_state_t *state = static_state(m);
    /* The device tick between detection and this call can invalidate fetch or
     * change RAM. Repeat the complete negative witness before skipping work. */
    if (!current_cached_unsupported(m, state)) return false;
    state->known_negative_bypasses++;
    return true;
#else
    (void)m;
    return false;
#endif
}

void s5l8900_static_a64_dispose(s5l8900_t *m) {
    if (!m) return;
#if defined(S5LBOX_STATIC_A64_ENGINE)
    free(m->static_a64_state);
#endif
    m->static_a64_state = NULL;
}
