/*
 * S5LBox — many configured machines, one running at a time.
 *
 * WHAT THIS IS. The app has had exactly one implicit machine: one set of
 * options, one guest, no name. Every other VM app people know — UTM, Parallels,
 * VirtualBox — instead keeps a LIST you pick from, and that is what this is: a
 * bounded, named, persistable set of instance records, each carrying its own
 * copy of the option table.
 *
 * WHAT IT IS NOT, and the distinction is load-bearing rather than a caveat.
 * "Multiple instances" here means many DEFINED, one RUNNING. It does not mean
 * two guests executing at once, and this file will not pretend otherwise:
 *
 *   - Guest DRAM is VM_GUEST_RAM_SIZE (128 MB) per machine, and the app's whole
 *     memory argument (see VMEngine.m's header) is that untouched guest RAM is
 *     address space rather than footprint because calloc hands back lazily
 *     faulted anonymous pages. That argument holds once. Two running guests
 *     both touching their framebuffers is 1.2 MB of scanout plus whatever the
 *     guests dirty, against a jetsam limit this project has not measured.
 *   - `core/` has no threading vocabulary at all. One emulator thread owns one
 *     machine for its lifetime. A second concurrent machine is not a UI change,
 *     it is a concurrency design nobody has done.
 *
 * So `vm_instance_list_t` deliberately has no "running" flag and no way to mark
 * two instances active. Whichever instance the UI opens is the one the single
 * engine runs. When concurrent execution is genuinely designed, THAT is when
 * this type grows a field for it — not before, and not speculatively.
 *
 * WHY PLAIN C11 AND NOT OBJECTIVE-C. Same reason as VMTouchMap, VMOptions and
 * VMTouchQueue: the parts of this that can be silently wrong are the parts a
 * host CI runner can test. Name validation, uniqueness, the bounded add, and
 * above all the round trip through the persisted form — a serialiser that
 * loses a field, or a parser that accepts a truncated file and returns a
 * plausible half-populated list, destroys somebody's configured machine and
 * reports nothing. None of that needs UIKit, so none of it lives in a .m file.
 *
 * Copyright (c) 2026 j0shua-SYSON. MIT licensed.
 */
#ifndef S5LBOX_APP_VMINSTANCES_H
#define S5LBOX_APP_VMINSTANCES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/*
 * How many machines the app will hold. Sixteen is a UI bound, not a technical
 * one: a phone-sized list stops being pickable long before it stops being
 * storable, and a fixed array keeps the whole store copyable and comparable
 * without an allocator. Hitting it is a named refusal, never a silent drop.
 */
#define VM_INSTANCE_MAX 16u

/*
 * The identifier is what names this instance's files on disk — its work image,
 * its snapshots — so it must be filename-safe on every host this project
 * builds for, and it must never change once chosen. Lower-case hex only:
 * 16 characters is 64 bits, which is not a UUID and does not need to be. It is
 * generated by the caller (the app uses arc4random), because a pure-C model
 * with no entropy source of its own should not pretend to have one.
 */
#define VM_INSTANCE_ID_LEN 16u

/*
 * The display name, in bytes of UTF-8 rather than characters. 48 bytes is
 * comfortably a phrase in any script and short enough for a table row; the
 * bound is on the ENCODED length because that is what the persisted form and
 * the fixed array actually cost.
 */
#define VM_INSTANCE_NAME_MAX 48u

/*
 * Per-instance option values. Sized above the option table rather than equal
 * to it so that adding a toggle to VMOptions does not silently truncate every
 * stored instance; vm_instance_options_fit() is the assertion that this bound
 * is still comfortable, and its test fails when the table outgrows it.
 */
#define VM_INSTANCE_OPTION_MAX 32u

typedef struct {
    char     id[VM_INSTANCE_ID_LEN + 1u];      /* NUL-terminated hex        */
    char     name[VM_INSTANCE_NAME_MAX + 1u];  /* NUL-terminated UTF-8      */
    uint64_t created_unix;                     /* 0 when unknown            */
    uint64_t last_opened_unix;                 /* 0 when never opened       */
    /*
     * Cumulative instructions this instance has retired across every session.
     * Recorded rather than derived because the engine is destroyed and rebuilt
     * on every start, so nothing else remembers.
     */
    uint64_t retired_total;
    /* One value per option-table row, in table order. Rows beyond
     * vm_option_count() are ignored and must stay false. */
    bool     options[VM_INSTANCE_OPTION_MAX];
} vm_instance_t;

typedef struct {
    vm_instance_t slot[VM_INSTANCE_MAX];
    unsigned      count;
} vm_instance_list_t;

/* Why an operation was refused. Every refusal is one of these — there is no
 * path that returns "failed" without saying which. */
typedef enum {
    VM_INSTANCE_OK = 0,
    VM_INSTANCE_ERR_NULL,          /* a required pointer was NULL           */
    VM_INSTANCE_ERR_FULL,          /* VM_INSTANCE_MAX already reached       */
    VM_INSTANCE_ERR_RANGE,         /* index past count                      */
    VM_INSTANCE_ERR_NAME_EMPTY,    /* empty, or only whitespace             */
    VM_INSTANCE_ERR_NAME_LONG,     /* over VM_INSTANCE_NAME_MAX bytes       */
    VM_INSTANCE_ERR_NAME_CONTROL,  /* contains a control byte or a newline  */
    VM_INSTANCE_ERR_ID_INVALID,    /* not exactly 16 lower-case hex digits  */
    VM_INSTANCE_ERR_ID_TAKEN,      /* another instance already has that id  */
    VM_INSTANCE_ERR_PARSE          /* the persisted form was not readable   */
} vm_instance_status_t;

/* One line, lower case, no full stop — for a log or an alert body. */
const char *vm_instance_status_text(vm_instance_status_t status);

/* Empty the list. Safe on a zeroed struct. */
void vm_instance_list_reset(vm_instance_list_t *list);

/*
 * Is a name acceptable, and is an id well-formed? Exposed separately so the UI
 * can grey out a Create button as the user types rather than only refusing on
 * submit. Leading and trailing whitespace is NOT trimmed here: the caller
 * decides whether to trim, and then asks.
 */
vm_instance_status_t vm_instance_name_check(const char *name);
vm_instance_status_t vm_instance_id_check(const char *id);

/*
 * Append an instance. `options` may be NULL for "all defaults false"; when
 * given, `option_count` values are copied and the rest stay false.
 * On success `*out_index` receives the new index when it is non-NULL.
 */
vm_instance_status_t vm_instance_add(vm_instance_list_t *list,
                                     const char *id, const char *name,
                                     const bool *options, unsigned option_count,
                                     uint64_t created_unix,
                                     unsigned *out_index);

/* Remove by index, preserving the order of the rest. */
vm_instance_status_t vm_instance_remove(vm_instance_list_t *list,
                                        unsigned index);

/* Rename in place. The id never changes — files on disk are named after it. */
vm_instance_status_t vm_instance_rename(vm_instance_list_t *list,
                                        unsigned index, const char *name);

/*
 * Copy an instance's CONFIGURATION under a new id and name. Deliberately not a
 * full clone: `retired_total` and `last_opened_unix` reset to zero, because
 * they describe a history the copy has not had, and nothing here copies the
 * work image the id names — that is the caller's, and it is a file operation.
 */
vm_instance_status_t vm_instance_duplicate(vm_instance_list_t *list,
                                           unsigned index,
                                           const char *new_id,
                                           const char *new_name,
                                           uint64_t created_unix,
                                           unsigned *out_index);

/* Index of the instance with this id, or -1 for NULL, a bad id, or no match. */
int vm_instance_index_of_id(const vm_instance_list_t *list, const char *id);

/* Row `index`, or NULL when out of range. */
const vm_instance_t *vm_instance_at(const vm_instance_list_t *list,
                                    unsigned index);

/*
 * ------------------------------------------------------------- persistence ---
 *
 * A line-oriented text form, not JSON and not a binary blob. Text because the
 * failure this most needs to survive is a half-written file after the app is
 * killed mid-save, and a text parser can reject a truncated record on its own
 * terms; not JSON because pulling in a parser to store five scalars would be
 * more code than the thing it stores.
 *
 * The format is versioned on its first line. An unknown version is
 * VM_INSTANCE_ERR_PARSE and loads NOTHING -- never a partial list, because a
 * partial list looks exactly like a user who deleted machines they did not
 * delete.
 */
#define VM_INSTANCE_FORMAT_VERSION 1u

/*
 * Render the whole list. snprintf semantics: returns the length the full text
 * would have had excluding the terminator, and writes at most `cap` bytes
 * including it. `out` may be NULL when `cap` is 0, so a caller can size the
 * buffer in one dry run.
 */
size_t vm_instance_serialize(const vm_instance_list_t *list,
                             char *out, size_t cap);

/*
 * Parse. On any error the list is left EMPTY rather than partly filled, and
 * the status says why. `text` must be NUL-terminated.
 */
vm_instance_status_t vm_instance_deserialize(vm_instance_list_t *list,
                                             const char *text);

/*
 * Does the live option table still fit VM_INSTANCE_OPTION_MAX? The app calls
 * this nowhere; its test does, so that outgrowing the bound is a red build
 * rather than a silent truncation of everyone's saved machines.
 */
bool vm_instance_options_fit(unsigned option_count);

#endif /* S5LBOX_APP_VMINSTANCES_H */
